#!/usr/bin/env node

import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const appName = "GrooveForge";
const bundleId = "app.grooveforge.desktop";
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
const platformArch = `${process.platform}-${process.arch}`;
const packageRoot = path.join(root, "build", "desktop", `${appName}-${platformArch}`);
const args = process.argv.slice(2);
const syntheticSmoke = args.includes("--smoke");
const forceOverwrite = args.includes("--force");
const reportStem = syntheticSmoke ? "release-channel-private-input-template-smoke" : "release-channel-private-input-template";
const markdownPath = path.join(packageRoot, `${appName}-${packageJson.version}-${platformArch}-${reportStem}.md`);
const jsonPath = path.join(packageRoot, `${appName}-${packageJson.version}-${platformArch}-${reportStem}.json`);
const syntheticRoot = path.join(packageRoot, reportStem);
const localEnvRootOverride = process.env.GROOVEFORGE_RELEASE_CHANNEL_TEMPLATE_ENV_ROOT?.trim() ?? "";
const resolvedLocalEnvRoot = syntheticSmoke
  ? syntheticRoot
  : localEnvRootOverride
    ? path.resolve(root, localEnvRootOverride)
    : root;
const relativeLocalEnvRoot = path.relative(root, resolvedLocalEnvRoot);
const privateInputFileKey = "GROOVEFORGE_RELEASE_CHANNEL_INPUT_FILE";
const defaultPrivateInputFileName = ".env.release-channel.local";
const configuredPrivateInputFileName = process.env[privateInputFileKey]?.trim() || defaultPrivateInputFileName;
const releaseChannelMetadataKeys = [
  "GROOVEFORGE_DISTRIBUTION_CHANNEL",
  "GROOVEFORGE_RELEASE_DOWNLOAD_URL",
  "GROOVEFORGE_RELEASE_NOTES_URL",
  "GROOVEFORGE_SUPPORT_URL"
];
const expectedShapes = new Map([
  ["GROOVEFORGE_DISTRIBUTION_CHANNEL", "allowed release channel token: direct-download, private-beta, or managed-release"],
  ["GROOVEFORGE_RELEASE_DOWNLOAD_URL", "safe absolute HTTPS URL for the release download"],
  ["GROOVEFORGE_RELEASE_NOTES_URL", "safe absolute HTTPS URL for release notes"],
  ["GROOVEFORGE_SUPPORT_URL", "safe absolute HTTPS URL for user support"]
]);
const placeholderValues = new Map([
  ["GROOVEFORGE_DISTRIBUTION_CHANNEL", "<direct-download|private-beta|managed-release>"],
  ["GROOVEFORGE_RELEASE_DOWNLOAD_URL", "<release-download-https-url>"],
  ["GROOVEFORGE_RELEASE_NOTES_URL", "<release-notes-https-url>"],
  ["GROOVEFORGE_SUPPORT_URL", "<support-https-url>"]
]);
const failures = [];

if ((syntheticSmoke || localEnvRootOverride) && (relativeLocalEnvRoot.startsWith("..") || path.isAbsolute(relativeLocalEnvRoot))) {
  console.error("GrooveForge release-channel private input template failed:");
  console.error("- Template env root must stay inside the repository.");
  process.exit(1);
}

function check(condition, message) {
  if (!condition) {
    failures.push(message);
  }
}

function relative(filePath) {
  return path.relative(root, filePath);
}

function readyLabel(value) {
  return value === true ? "yes" : "no";
}

function escapeCell(value) {
  return String(value ?? "none").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function privateInputCandidatePath() {
  const candidatePath = path.isAbsolute(configuredPrivateInputFileName)
    ? configuredPrivateInputFileName
    : path.resolve(resolvedLocalEnvRoot, configuredPrivateInputFileName);
  const relativeCandidate = path.relative(resolvedLocalEnvRoot, candidatePath);
  if (relativeCandidate.startsWith("..") || path.isAbsolute(relativeCandidate)) {
    console.error("GrooveForge release-channel private input template failed:");
    console.error("- Private release-channel input file must stay inside the selected env root.");
    process.exit(1);
  }
  return candidatePath;
}

function displayLocalEnvTarget(filePath) {
  const relativePath = path.relative(root, filePath);
  if (!relativePath.startsWith("..") && !path.isAbsolute(relativePath)) {
    return relativePath;
  }
  return path.basename(filePath);
}

function buildTemplateRows(filePath) {
  const target = displayLocalEnvTarget(filePath);
  return releaseChannelMetadataKeys.map((key, index) => ({
    order: index + 1,
    key,
    placeholder: placeholderValues.get(key),
    expectedShape: expectedShapes.get(key),
    targetFile: target,
    preflightCommand: "npm run release:channel-apply-private-env-preflight",
    writeCommand: "npm run release:channel-apply-private-env",
    proofCommand: "npm run release:private-edit-strict-proof",
    valueRecorded: false
  }));
}

function renderTemplate(rows) {
  return [
    "# GrooveForge release-channel private input file.",
    "# Generated by npm run release:channel-private-input-template.",
    "# This file is ignored by git. Replace placeholders locally and never commit real values.",
    "# After editing, run npm run release:channel-apply-private-env-preflight.",
    "",
    ...rows.map((row) => `${row.key}=${row.placeholder}`),
    ""
  ].join("\n");
}

function formatTemplateRows(rows) {
  return rows
    .map(
      (row) =>
        `| ${row.order} | ${escapeCell(row.key)} | ${escapeCell(row.placeholder)} | ${escapeCell(row.expectedShape)} | ${escapeCell(row.targetFile)} | \`${escapeCell(row.preflightCommand)}\` | \`${escapeCell(row.writeCommand)}\` | \`${escapeCell(row.proofCommand)}\` | ${readyLabel(row.valueRecorded)} |`
    )
    .join("\n");
}

function buildMarkdown(report) {
  return `# ${appName} Release-Channel Private Input Template

## Summary

- Template ready: ${readyLabel(report.releaseChannelPrivateInputTemplateReady)}
- Synthetic smoke: ${readyLabel(report.syntheticSmoke)}
- Force overwrite requested: ${readyLabel(report.forceOverwrite)}
- Template file present before run: ${readyLabel(report.templateFilePresentBefore)}
- Template file written: ${readyLabel(report.templateFileWritten)}
- Template file skipped because present: ${readyLabel(report.templateFileSkippedExisting)}
- Template file path: ${report.templateFilePath}
- Private input file key: \`${report.privateInputFileKey}\`
- Private input file default: \`${report.privateInputFileDefaultName}\`
- Operator private input file default path: \`${report.operatorPrivateInputFileDefaultPath}\`
- Current required keys: ${report.currentRequiredKeyCount} (${report.currentRequiredKeySummary})
- Template rows: ${report.templateRowCount}
- Current operator first command after editing: \`${report.currentOperatorFirstCommand}\`
- Next write command after preflight: \`${report.nextWriteCommand}\`
- Recommended proof chain after apply: \`${report.recommendedOperatorProofCommand}\`
- Guided setup fallback command: \`${report.guidedSetupFallbackCommand}\`
- Private input file values recorded: no
- Network probe attempted: no
- Release upload attempted: no
- Apple notary submission attempted: no
- Signing attempted: no
- External distribution claimed: no

## Template Rows

| order | key | placeholder | expected shape | target file | preflight command | write command | proof command | value recorded |
|---:|---|---|---|---|---|---|---|---:|
${formatTemplateRows(report.templateRows)}

## Command Chain

1. \`${report.reportCommand}\` to create the ignored private input file skeleton when it is missing.
2. \`${report.currentOperatorFirstCommand}\` after replacing placeholders locally.
3. \`${report.nextWriteCommand}\` after preflight reports 4/4 shape-ready private inputs.
4. \`${report.recommendedOperatorProofCommand}\` after the apply command writes 4/4 current-ready rows.

## Not Recorded

This report records key names, placeholder markers, expected shape labels, file names, command names, and row counts only. It does not record release URLs, support URLs, channel values, credentials, tokens, Developer ID identity labels, local env values, private beats, or real user audio.

## Not Claimed

This command does not claim Developer ID signing, notarization, Gatekeeper approval, auto-update readiness, manual QA approval, release upload, app-store submission, remote channel probing, or external distribution completion.
`;
}

async function writeReport(report) {
  const markdown = buildMarkdown(report);
  const json = `${JSON.stringify(report, null, 2)}\n`;
  const combined = `${markdown}\n${json}`;
  check(!/https?:\/\//i.test(combined), "release-channel private input template report should not include URL values");
  check(!combined.includes("downloads.invalid"), "release-channel private input template report should not include synthetic URL host values");
  check(!combined.includes("support.invalid"), "release-channel private input template report should not include synthetic support host values");
  await mkdir(packageRoot, { recursive: true });
  await writeFile(markdownPath, markdown, "utf8");
  await writeFile(jsonPath, json, "utf8");
}

async function main() {
  const templateFilePath = privateInputCandidatePath();
  const templateRows = buildTemplateRows(templateFilePath);
  const templateText = renderTemplate(templateRows);
  const templateFilePresentBefore = existsSync(templateFilePath);
  const shouldWriteTemplate = syntheticSmoke || forceOverwrite || templateFilePresentBefore === false;
  let templateFileWritten = false;

  if (shouldWriteTemplate) {
    await mkdir(path.dirname(templateFilePath), { recursive: true });
    await writeFile(templateFilePath, templateText, "utf8");
    templateFileWritten = true;
  }

  const report = {
    appName,
    bundleId,
    version: packageJson.version,
    generatedAt: new Date().toISOString(),
    platform: process.platform,
    arch: process.arch,
    platformArch,
    reportCommand: syntheticSmoke
      ? "npm run release:channel-private-input-template-smoke"
      : "npm run release:channel-private-input-template",
    releaseChannelPrivateInputTemplateMarkdownPath: relative(markdownPath),
    releaseChannelPrivateInputTemplateJsonPath: relative(jsonPath),
    syntheticSmoke,
    forceOverwrite,
    localEnvRootOverrideEnabled: Boolean(localEnvRootOverride) || syntheticSmoke,
    localEnvRootRelativePath: syntheticSmoke || localEnvRootOverride ? relativeLocalEnvRoot : ".",
    privateInputFileKey,
    privateInputFileDefaultName: defaultPrivateInputFileName,
    operatorPrivateInputFileDefaultPath: defaultPrivateInputFileName,
    configuredPrivateInputFileName,
    templateFilePath: displayLocalEnvTarget(templateFilePath),
    templateFilePresentBefore,
    templateFilePresentAfter: existsSync(templateFilePath),
    templateFileWritten,
    templateFileSkippedExisting: templateFilePresentBefore === true && templateFileWritten === false,
    realPrivateInputFileRead: false,
    realPrivateInputFileModified: resolvedLocalEnvRoot === root && templateFileWritten === true,
    templateRows,
    templateRowCount: templateRows.length,
    currentRequiredKeys: releaseChannelMetadataKeys,
    currentRequiredKeyCount: releaseChannelMetadataKeys.length,
    currentRequiredKeySummary: releaseChannelMetadataKeys.join(", "),
    currentOperatorFirstCommand: "npm run release:channel-apply-private-env-preflight",
    nextWriteCommand: "npm run release:channel-apply-private-env",
    firstStrictProofCommand: "npm run release:channel-live-check-strict",
    recommendedOperatorProofCommand: "npm run release:private-edit-strict-proof",
    guidedSetupFallbackCommand: "npm run release:channel-setup-wizard",
    currentBlockerCommand: "npm run release:current-blocker",
    hardGateCommand: "npm run release:external-check",
    releaseChannelPrivateInputTemplateReady: existsSync(templateFilePath) && templateRows.length === releaseChannelMetadataKeys.length,
    privateInputFileValueRecorded: false,
    privateValuesRecorded: false,
    localEnvValueRecorded: false,
    releaseUrlValueRecorded: false,
    supportUrlValueRecorded: false,
    channelValueRecorded: false,
    networkProbeAttempted: false,
    releaseUploadAttempted: false,
    notarySubmissionAttempted: false,
    signingAttempted: false,
    releaseGateClaimedDeveloperIdSigning: false,
    releaseGateClaimedNotarization: false,
    releaseGateClaimedGatekeeperApproval: false,
    releaseGateClaimedAutoUpdate: false,
    releaseGateClaimedManualQaApproval: false,
    releaseGateClaimedExternalDistribution: false,
    valueRecorded: false
  };

  check(report.currentRequiredKeyCount === 4, "release-channel private input template should cover four release-channel keys");
  check(report.templateRowCount === 4, "release-channel private input template should write four template rows");
  check(report.templateRows.every((row) => releaseChannelMetadataKeys.includes(row.key)), "release-channel private input template rows should be limited to release-channel keys");
  check(report.templateRows.every((row) => row.valueRecorded === false), "release-channel private input template rows should be value-free");
  check(report.privateInputFileKey === privateInputFileKey, "release-channel private input template should expose the private input file key");
  check(report.privateInputFileDefaultName === defaultPrivateInputFileName, "release-channel private input template should expose the default private input file name");
  check(report.operatorPrivateInputFileDefaultPath === defaultPrivateInputFileName, "release-channel private input template should expose the operator default path");
  check(report.currentOperatorFirstCommand === "npm run release:channel-apply-private-env-preflight", "release-channel private input template should point to preflight first");
  check(report.nextWriteCommand === "npm run release:channel-apply-private-env", "release-channel private input template should point to apply after preflight");
  check(report.recommendedOperatorProofCommand === "npm run release:private-edit-strict-proof", "release-channel private input template should point to the strict proof chain");
  check(report.guidedSetupFallbackCommand === "npm run release:channel-setup-wizard", "release-channel private input template should keep guided setup as fallback");
  check(report.realPrivateInputFileRead === false, "release-channel private input template should not read real private input values");
  check(!syntheticSmoke || report.realPrivateInputFileModified === false, "release-channel private input template smoke should not modify the real private input file");
  check(report.privateValuesRecorded === false, "release-channel private input template should not record private values");
  check(report.localEnvValueRecorded === false, "release-channel private input template should not record local env values");
  check(report.releaseUrlValueRecorded === false, "release-channel private input template should not record release URL values");
  check(report.supportUrlValueRecorded === false, "release-channel private input template should not record support URL values");
  check(report.channelValueRecorded === false, "release-channel private input template should not record channel values");
  check(report.networkProbeAttempted === false, "release-channel private input template should not probe networks");
  check(report.releaseUploadAttempted === false, "release-channel private input template should not upload releases");
  check(report.notarySubmissionAttempted === false, "release-channel private input template should not submit notarization");
  check(report.signingAttempted === false, "release-channel private input template should not sign artifacts");
  check(report.releaseGateClaimedExternalDistribution === false, "release-channel private input template should not claim external distribution");

  await writeReport(report);

  if (failures.length > 0 || report.releaseChannelPrivateInputTemplateReady !== true) {
    console.error("GrooveForge release-channel private input template failed.");
    console.error(`- Markdown: ${relative(markdownPath)}`);
    console.error(`- JSON: ${relative(jsonPath)}`);
    console.error(`- Synthetic smoke: ${readyLabel(report.syntheticSmoke)}`);
    console.error(`- Template file path: ${report.templateFilePath}`);
    console.error(`- Template file present before run: ${readyLabel(report.templateFilePresentBefore)}`);
    console.error(`- Template file written: ${readyLabel(report.templateFileWritten)}`);
    console.error(`- Template rows: ${report.templateRowCount}`);
    console.error(`- Next preflight: ${report.currentOperatorFirstCommand}`);
    console.error(`- Next write command: ${report.nextWriteCommand}`);
    console.error(`- Next proof after apply: ${report.recommendedOperatorProofCommand}`);
    console.error("- Private values recorded: no");
    console.error("- Network: no distribution channel probe, release upload, Apple notary submission, or signing attempted");
    console.error("- Not claimed: Developer ID signing, notarization, Gatekeeper approval, auto-update, manual QA approval, app-store submission, or external distribution completion");
    for (const failure of failures) {
      console.error(`- ${failure}`);
    }
    process.exit(1);
  }

  console.log("GrooveForge release-channel private input template passed.");
  console.log(`- Markdown: ${relative(markdownPath)}`);
  console.log(`- JSON: ${relative(jsonPath)}`);
  console.log(`- Synthetic smoke: ${readyLabel(report.syntheticSmoke)}`);
  console.log(`- Force overwrite requested: ${readyLabel(report.forceOverwrite)}`);
  console.log(`- Template file path: ${report.templateFilePath}`);
  console.log(`- Template file present before run: ${readyLabel(report.templateFilePresentBefore)}`);
  console.log(`- Template file written: ${readyLabel(report.templateFileWritten)}`);
  console.log(`- Template file skipped because present: ${readyLabel(report.templateFileSkippedExisting)}`);
  console.log(`- Template rows: ${report.templateRowCount}`);
  console.log(`- Private input file key: ${report.privateInputFileKey}`);
  console.log(`- Private input file default: ${report.privateInputFileDefaultName}`);
  console.log(`- Operator private input file default path: ${report.operatorPrivateInputFileDefaultPath}`);
  console.log(`- Next preflight: ${report.currentOperatorFirstCommand}`);
  console.log(`- Next write command: ${report.nextWriteCommand}`);
  console.log(`- Guided setup fallback: ${report.guidedSetupFallbackCommand}`);
  console.log(`- Next proof after apply: ${report.recommendedOperatorProofCommand}`);
  console.log("- Private values recorded: no");
  console.log("- Network: no distribution channel probe, release upload, Apple notary submission, or signing attempted");
  console.log("- Not claimed: Developer ID signing, notarization, Gatekeeper approval, auto-update, manual QA approval, app-store submission, or external distribution completion");
}

await main();
