#!/usr/bin/env python3
"""Validate the GrooveForge project base."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PLAN_RE = re.compile(r"plan-\d{3}-[a-z0-9][a-z0-9-]*\.md$")

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "package.json",
    "index.html",
    "vite.config.ts",
    "tsconfig.json",
    "tsconfig.electron.json",
    "electron/main.ts",
    "electron/preload.ts",
    "src/main.tsx",
    "src/ui/App.tsx",
    "src/audio/midi.ts",
    "src/domain/workstation.ts",
    "src/audio/render.ts",
    "src/audio/scheduler.ts",
    "src/styles.css",
    "docs/architecture/harness.md",
    "docs/architecture/product-architecture.md",
    "docs/product/product.md",
    "docs/quality/rules.md",
    "docs/privacy/principles.md",
    "docs/references/official-sources.md",
    "docs/exec_plans/active",
    "docs/exec_plans/completed",
    "docs/meetings/index.md",
    "docs/reviews",
    "harness/templates/exec-plan.md",
    "harness/templates/meeting.md",
    "harness/templates/review.md",
]

TEXT_EXPECTATIONS = {
    "README.md": [
        "making beats across genres",
        "beat workstation first, not a sampler-first app",
        "Direct composition is the product spine",
        "program drums, 808/bass, melody, chords, FX, and automation as editable musical events",
        "opening a compact beat-making DAW, not a sample browser",
        "Sampling is a secondary add-on.",
        "A complete GrooveForge beat must be possible with no imported audio.",
        "If a draft, screen, or roadmap has to choose what appears first, the answer is direct beat creation",
        "Keep first-run UI and default navigation focused on making beats across genres",
        "Treat sample-free beat creation as the proof of the product",
        "local project save/load",
        "Key changes that retarget Pattern A/B/C 808, synth, and chord-root event data",
        "Style selector that applies editable genre groove templates",
        "Beat Blueprints for sample-free project starts that apply style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset while staying fully editable.",
        "drum velocity, event chance, chance badges, microtiming, one-click groove humanization, hat repeat dynamics, and selected-note move/transpose/duplicate tools",
        "Key-aware chord progression presets with chord add/delete, selected-chord move/duplicate/inversion tools, and per-chord chance controls",
        "kick-to-808 sidechain ducking",
        "Independent Pattern A/B/C variations with deterministic Subtle/Hook/Break tools, copy/clear tools, and editable arrangement blocks with one-click Drop/Build/Hook Lift moves, per-track mutes, audible energy, bar length, split, merge, duplicate, move, and delete controls",
        "Read-only Beat Readiness checks for drums, 808, melody/chords, arrangement, and export completeness.",
        "Arrangement templates for 8-bar loop, full beat, hook-first, and breakdown song structures with explicit section lengths.",
        "Desktop editing shortcuts for arrangement playback, Pattern A/B/C switching, selected event deletion, save, open, undo, and redo.",
        "Undo/redo edit history",
        "Realtime transport metronome toggle with accented downbeat clicks",
        "Live playback that follows future pattern, arrangement track mutes, BPM, mixer, sound, and master edits without forcing users to stop and restart.",
        "one-click Drop/Build/Hook Lift moves, per-track mutes, per-block bar lengths, split/merge controls, and audible energy",
        "Basic mixer volume/pan/mute/solo, channel low-cut/air EQ, Drive/Glue mix controls, Space send FX",
        "per-stem export level meters",
        "deterministic Mix Coach checks",
        "arrangement MIDI export for DAW handoff",
        "reproducible export peak/RMS/headroom meter",
        "transport with arrangement playback, Pattern preview, and a realtime-only metronome",
        "Beat Blueprints for sample-free editable project starts",
        "deterministic Pattern variation tools",
        "editable scale-aware 808/melody lanes with note chance badges and selected-note move/transpose/duplicate tools",
        "channel low-cut/air EQ",
        "Drive/Glue mix controls",
        "chord progression presets plus add/delete/selected-chord move/duplicate/inversion/chance controls",
        "Sound presets and Studio tone controls",
        "read-only Beat Readiness checks",
        "Space send FX",
        "per-stem export level meters",
        "deterministic Mix Coach checks",
        "reproducible export peak/RMS/headroom meter",
        "one-click stem export",
        "arrangement MIDI export",
        "npm run desktop",
    ],
    "AGENTS.md": [
        "No Exec Plan, No Work",
        "GrooveForge is an all-genre, event-based beat workstation",
        "First-run UI, default navigation, and roadmap order should lead with direct beat composition",
    ],
    "docs/product/product.md": [
        "It is beat-first, not sampler-first.",
        "The center is making a beat directly, not finding a sample to start from.",
        "Pattern programming for all supported styles.",
        "Optional sampling module, later and outside the MVP:",
        "No user should need a sample to make the first complete beat.",
        "When sampling appears later, it should behave like an optional sound source or instrument layer inside the beat workstation",
        "샘플 없이도 8마디 비트를 만들고 WAV로 export할 수 있어야 한다.",
        "This sentence supersedes any sampling-first interpretation of the brief.",
        "Sampling can be useful, but it must stay behind the composition engine",
        "Primary navigation and the first empty project should expose beat-making controls before sample workflows",
        "Sampling entry points, when added, should be opt-in secondary paths",
        "it means a pattern, MIDI, or automation container",
        "Local project save/load",
        "Key changes retarget Pattern A/B/C 808/bass, melody, and chord-root musical events",
        "Style selector that applies key-aware editable groove templates",
        "Beat blueprints: sample-free editable project starts that combine style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset.",
        "Beat Blueprints that apply complete sample-free project starts across style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset while preserving manual editing.",
        "editable drum velocity, probability, visible chance badges, microtiming, one-click groove humanization, and hat repeat dynamics",
        "note chance badges, selected-note move/transpose/duplicate tools, saturation direction, and kick-to-808 sidechain ducking",
        "kick-to-808 sidechain ducking",
        "sidechain ducking",
        "editable step/root/quality/inversion/length/velocity/chance, visible chance badges, add/delete controls, and selected-chord move/duplicate/inversion tools",
        "Independent Pattern A/B/C storage with deterministic Subtle/Hook/Break variation tools plus copy/clear tools for drum, bass, chord, and melody variations",
        "Read-only Beat Readiness checks for drums, 808/bass, melody/chords, arrangement structure, and export signal status.",
        "Undo/redo edit history for project-level pattern, arrangement, mixer, sound, and master changes",
        "Desktop editing shortcuts for arrangement playback, Pattern A/B/C selection, selected drum/note deletion, save, open, undo, and redo",
        "Transport playback modes for full arrangement playback by default and fast selected-pattern preview while editing.",
        "Realtime metronome toggle with accented downbeat clicks",
        "without adding click audio to WAV or stem export",
        "Live playback reads the current project while scheduling future steps",
        "selected-pattern preview, arrangement block edits, arrangement track mutes, arrangement length, arrangement energy, BPM, mixer, sound, and master changes can be heard without stopping and restarting",
        "Chord progression track with scale-locked roots, key-aware progression presets",
        "editable step/root/quality/inversion/length/velocity/chance, visible chance badges, add/delete controls, and selected-chord move/duplicate/inversion tools",
        "Simple synth melody track with editable scale-aware grid, velocity control, note chance badges, and selected-note move/transpose/duplicate tools.",
        "Sound design presets and Studio tone controls",
        "Editable arrangement blocks and templates",
        "one-click Drop/Build/Hook Lift moves",
        "8-bar loop, full beat, hook-first, and breakdown structures",
        "per-block track mutes",
        "audible per-block energy",
        "per-block bar length",
        "split/merge controls",
        "duplicate, move, and delete controls",
        "Mixer volume, pan, mute, solo, low-cut/air EQ, Drive/Glue mix controls, built-in Space send FX, per-stem export level meters, and deterministic Mix Coach checks reflected in deterministic render feedback",
        "channel low-cut/air EQ",
        "Drive/Glue mix controls",
        "per-stem export level meters",
        "deterministic Mix Coach checks",
        "Reproducible export peak/RMS/headroom meter with limiter activity status",
        "WAV export through deterministic offline rendering",
        "Stem export through deterministic offline rendering",
        "MIDI export as a deterministic Standard MIDI File with drum, 808, synth, and chord tracks from the current arrangement.",
        "Feature priority follows the beat-workstation core:",
        "P3 | sampling and plugin hosting",
    ],
    "docs/quality/rules.md": [
        "QA and review are separate loops.",
        "python3 harness/scripts/run_quality_gate.py",
        "Metronome work must keep click playback realtime-only",
        "keep WAV/stem exports free of metronome audio",
        "Drum probability work must migrate old patterns to 100% chance",
        "808, melody, and chord chance work must migrate older musical events to 100% chance",
        "Chance badge work must keep badges read-only",
        "use deterministic probability gates so exported audio is reproducible",
        "Project file work must reject invalid imports",
        "preserve edited drum, bass, chord, melody, sound design",
        "Drum dynamics work must migrate old patterns",
        "Drum microtiming work must migrate old patterns",
        "Groove humanize work must be deterministic",
        "Style groove work must apply key-aware editable Pattern A/B/C event data",
        "Beat Blueprint work must apply deterministic sample-free project starts from local style, key, BPM, Pattern A/B/C event data, arrangement templates, sound presets, mixer balance, and master presets",
        "keep the result fully editable and undoable",
        "Key retarget work must update Pattern A/B/C 808/bass note pitches, melody note pitches, and chord roots by scale degree",
        "Chord progression work must preserve Pattern A/B/C independence",
        "keep chord roots and progression presets scale-aware by default",
        "keep add/delete operations undoable",
        "preserve at least one chord event in guided editing",
        "Chord inversion work must migrate older chord events to root position",
        "Selected chord edit tool work must keep chord move, duplicate, delete, and inversion actions scoped to the selected Pattern A/B/C slot",
        "avoid overlapping duplicate or moved chord starts at the same step",
        "Sound design work must keep tone parameters in project state",
        "Sidechain work must keep kick-to-808 ducking",
        "Export meter work must label measurements honestly as peak, RMS, headroom, and limiter activity",
        "Render noise work must keep offline WAV export, stem export, and export meter analysis deterministic from render-relevant project data",
        "avoid `Math.random()` in the offline render path",
        "Stem export work must render isolated drum, 808, synth, and chord WAV files",
        "Stem level meter work must derive drum, 808, synth, and chord meter values from the deterministic offline stem render path",
        "show peak/RMS/headroom honestly without LUFS or true-peak claims",
        "Mix Coach work must derive suggestions only from deterministic full-mix and stem export analysis",
        "communicate peak/RMS/headroom/limiter/stem-balance checks without LUFS, true-peak, platform compliance, or mastering-fix claims",
        "MIDI export work must write deterministic Standard MIDI Files from editable project events",
        "Pattern work must keep Pattern A/B/C as independent editable event data",
        "Copy and clear tools must operate on the selected pattern slot",
        "Pattern preview playback should loop the selected pattern",
        "arrangement playback and WAV export should follow arrangement pattern assignments",
        "Pattern variation work must be deterministic",
        "operate only on the selected Pattern A/B/C slot through undoable project history",
        "keep generated drums, bass, melody, chords, velocities, timings, repeats, and probabilities manually editable",
        "Beat Readiness work must derive checks from editable Pattern A/B/C, arrangement, and deterministic export analysis data",
        "remain read-only, avoid mutating project state or generating musical events",
        "Selected note edit tool work must keep 808 and Synth note move, transpose, octave, and duplicate actions scoped to the selected Pattern A/B/C slot",
        "preserve length/glide/velocity/chance fields",
        "avoid overlapping duplicate notes at the same step and pitch",
        "Arrangement editor work must let users change a block's section",
        "bar length, and energy",
        "Arrangement track mute work must migrate older arrangement blocks to no muted tracks",
        "keep mutes scoped to the selected block without mutating Pattern A/B/C events",
        "apply the same mute decisions to realtime arrangement playback, full-mix WAV export, and stem export",
        "Arrangement structure work must preserve at least one block",
        "Arrangement split work must split only the selected arrangement block",
        "preserve total arrangement bars",
        "Arrangement merge work must merge only the selected block with the next block",
        "keep the selected block's section",
        "Arrangement template work must replace only arrangement blocks",
        "align the selected pattern with the first template block",
        "make WAV/stem export follow the applied template length",
        "Arrangement length work must keep per-block bar counts bounded",
        "migrate older project files without bar counts to one bar per block",
        "make export meter, full-mix WAV export, and stem export follow total arrangement bars",
        "Arrangement playback work must map realtime playback through arrangement blocks",
        "preserving a selected-pattern preview mode",
        "accurate transport status",
        "Arrangement energy work must keep Energy as deterministic arrangement-block playback/render interpretation",
        "apply the same gain rule to realtime arrangement playback, WAV export, and stem export",
        "preserve selected-pattern preview at neutral energy",
        "Arrangement Move work must transform only the selected arrangement block's existing energy and mutedTracks state through undoable project history",
        "keep Drop/Build/Hook Lift/Reset deterministic and editable afterward",
        "Live playback edit work must read current project state while scheduling future steps",
        "already-triggered audio is not rewritten",
        "Undo/redo work must record bounded local project-edit history",
        "keep keyboard shortcuts out of focused inputs",
        "Desktop shortcut work must keep playback, Pattern A/B/C selection, save/open, undo/redo, and selected event deletion scoped to the app window",
        "must route destructive deletion through normal undoable project history",
        "Volume, pan, mute, solo, master output gain, and preset ceiling controls",
        "Channel EQ work must keep low-cut/air controls in mixer state",
        "Channel dynamics work must keep Drive/Glue controls in mixer state",
        "FX send work must keep Space/send controls in mixer state",
        "simplified compression honestly",
        "full-mix WAV export, and stem export",
        "sample import, chopping, sampler tracks, or audio warping",
        "First-run UX, default navigation, and roadmap work must lead with direct beat composition",
        "Sample browsing, chopping, sampler setup, audio clips, and audio warping must stay opt-in optional-sampling paths",
        "core clips are pattern, MIDI, or automation containers",
    ],
    "docs/architecture/product-architecture.md": [
        "Pattern/Event Clips",
        "not an imported audio asset",
        "Sampling architecture should attach to the beat workstation",
        "The core architecture should remain valid with no audio-file entities at all.",
        "Key and scale changes are composition edits over musical event data.",
        "sample browsing, chopping, sampler mapping, and audio warping belong behind explicit optional-sampling entry points",
        "Roadmap and architecture plans should treat `audio` and `sampler` as extension track types until the direct beat workstation is already useful.",
        "Extension track types for optional sampling, later:",
    ],
    "harness/scripts/run_qa.py": [
        '".worktree/"',
    ],
    "docs/references/official-sources.md": [
        "W3C Web Audio API",
        "Electron Docs",
        "Vite Guide",
        "ITU-R BS.1770",
        "Source Gaps",
    ],
    "package.json": [
        "\"desktop\"",
        "\"typecheck\"",
        "\"build\"",
    ],
    "electron/main.ts": [
        "nodeIntegration: false",
        "contextIsolation: true",
        "sandbox: true",
        "grooveforge:save-project",
        "grooveforge:open-project",
    ],
    "electron/preload.ts": [
        "saveProject",
        "openProject",
    ],
    "src/ui/App.tsx": [
        "Guided",
        "Studio",
        "exportMidi",
        "exportWav",
        "exportStems",
        "analyzeExport",
        "ExportMeter",
        "export-meter-status",
        "export-peak-db",
        "export-rms-db",
        "export-headroom-db",
        "export-limiter-percent",
        "master-ceiling",
        "startRealtimePlayback",
        "getProject: () => projectRef.current",
        "metronome-toggle",
        "toggleMetronome",
        "PlaybackMode",
        "playbackMode",
        "playback-mode-arrangement",
        "playback-mode-pattern",
        "transportPrimary",
        "transportSecondary",
        "currentPatternStep",
        "createStylePatternSet",
        "styleSoundPreset",
        "Applied ${nextStyle.name} groove",
        "BeatBlueprintId",
        "BeatBlueprints",
        "applyBeatBlueprint",
        "applySelectedBeatBlueprint",
        "beatBlueprints",
        "beat-blueprints",
        "beat-blueprint-current",
        "beat-blueprint-${blueprint.id}",
        "retargetProjectKey",
        "applyProjectKey",
        "Retargeted project to ${key}",
        "DrumStepInspector",
        "drum-probability",
        "drum-probability-input",
        "drum-chance-badge-${lane}-${step}",
        "updateSelectedDrumProbability",
        "chance / ${timingLabel",
        "selectedDrumStep",
        "updateSelectedDrumVelocity",
        "updateSelectedHatRepeat",
        "drum-velocity",
        "drum-velocity-input",
        "drum-timing-early",
        "drum-timing-on",
        "drum-timing-late",
        "drum-timing-input",
        "updateSelectedDrumTiming",
        "applySelectedDrumGroove",
        "groove-preset-${preset}",
        "timingLabel",
        "timingBadge",
        "hat-repeat-${repeat}",
        "undoStack",
        "redoStack",
        "undoProject",
        "redoProject",
        "handleDesktopShortcut",
        "deleteSelectedEvent",
        "deleteSelectedNote",
        "clearSelectedDrumStep",
        "wantsSave",
        "wantsOpen",
        "event.code === \"Space\"",
        "patternShortcut",
        "undo-button",
        "redo-button",
        "isEditableShortcutTarget",
        "historyLimit",
        "NoteEditor",
        "toggleBassNote",
        "toggleMelodyNote",
        "selectedSameNote",
        "NoteInspector",
        "note-probability",
        "note-probability-input",
        "note-chance-badge-${track}-${step}-${pitch}",
        "updateSelectedNoteProbability",
        "moveSelectedNoteStep",
        "moveSelectedNotePitch",
        "moveSelectedNoteOctave",
        "moveSelectedNoteTo",
        "duplicateSelectedNote",
        "note-nudge-left",
        "note-nudge-right",
        "note-pitch-down",
        "note-pitch-up",
        "note-octave-down",
        "note-octave-up",
        "note-duplicate",
        "adjacentTrackPitch",
        "octaveShiftPitch",
        "nextEmptyStepForPitch",
        "SoundDesigner",
        "SoundControl",
        "commitPercentInput",
        "skipNextBlurCommit",
        "applySoundPreset",
        "updateSoundDesign",
        "sound-preset-readout",
        "sound-preset-${preset}",
        "sound-${id}-input",
        "bass-drive",
        "sidechain-duck",
        "sound-duck-readout",
        "chord-width",
        "ChordEditor",
        "chordInversions",
        "chordInversionLabel",
        "ChordProgressionPreset",
        "selectedChordIndex",
        "selectChordEvent",
        "chordProgressionPresetIds",
        "chordProgressionPresetLabel",
        "createChordProgressionPreset",
        "createNextChordEvent",
        "applyChordProgressionPreset",
        "addChordEvent",
        "deleteChordEvent",
        "deleteSelectedChordEvent",
        "updateChordEvent",
        "moveSelectedChordStep",
        "duplicateSelectedChord",
        "moveSelectedChordInversion",
        "chordEventWithUpdate",
        "sameChordEvent",
        "findChordEventIndex",
        "nextEmptyChordStep",
        "chord-preset-${preset}",
        "chord-add",
        "chord-delete",
        "chord-move-left",
        "chord-move-right",
        "chord-duplicate",
        "chord-invert-down",
        "chord-invert-up",
        "chord-step",
        "chord-root",
        "chord-quality",
        "chord-inversion",
        "chord-inversion-badge",
        "chord-length-input",
        "chord-velocity-input",
        "chord-probability-input",
        "chord-chance-badge-${index}",
        "chanceBadgeLabel",
        "compactChanceBadgeLabel",
        "handleSaveProject",
        "handleOpenProject",
        "handleExportMidi",
        "Exported MIDI",
        "handleExportStems",
        "export-midi",
        "export-stems",
        "Invalid project file",
        "patternEventCount",
        "BeatReadiness",
        "BeatReadinessCheck",
        "createBeatReadinessChecks",
        "arrangedPatternData",
        "drumHitCount",
        "drumReadinessCheck",
        "bassReadinessCheck",
        "harmonyReadinessCheck",
        "arrangementReadinessCheck",
        "exportReadinessCheck",
        "beatReadinessChecks",
        "beat-readiness",
        "beat-readiness-summary",
        "beat-readiness-check-${check.id}",
        "selectPattern",
        "copySelectedPattern",
        "clearSelectedPattern",
        "applyPatternVariation",
        "patternVariationPresetIds",
        "patternVariationPresetLabel",
        "pattern-copy-${pattern}",
        "pattern-variation-${preset}",
        "pattern-clear",
        "selectedArrangementIndex",
        "ArrangementTemplateId",
        "arrangementTemplateIds",
        "arrangementTemplateLabel",
        "ArrangementMovePreset",
        "arrangementMovePresetIds",
        "arrangementMovePresetLabel",
        "applyArrangementMovePreset",
        "applyArrangementMoveToSelected",
        "arrangementMuteTrackIds",
        "arrangementMuteTrackLabel",
        "arrangementTotalBars",
        "createArrangementTemplate",
        "minArrangementBars",
        "maxArrangementBars",
        "arrangementEnergyGain",
        "normalizeArrangementEnergy",
        "normalizeArrangementMutedTracks",
        "normalizeArrangementBars",
        "applyArrangementTemplate",
        "updateArrangementBlock",
        "toggleArrangementTrackMute",
        "duplicateArrangementBlock",
        "splitArrangementBlock",
        "mergeArrangementBlock",
        "canMergeArrangementBlock",
        "selectedArrangementNextBlock",
        "splitAfterBars",
        "clampSplitAfterBars",
        "moveArrangementBlock",
        "deleteArrangementBlock",
        "Merged arrangement blocks",
        "Selected arrangement block editor",
        "arrangement-template-${template}",
        "arrangement-section-select",
        "arrangement-bars-input",
        "arrangement-split-after",
        "arrangement-split",
        "arrangement-merge",
        "arrangement-energy-input",
        "arrangement-move-${preset}",
        "arrangement-track-mute-${track}",
        "arrangement-duplicate",
        "arrangement-delete",
        "barCountLabel",
        "updateMixerChannel",
        "normalizeMixerEq",
        "mixer-low-cut",
        "mixer-low-cut-input",
        "mixer-air",
        "mixer-air-input",
        "mixer-drive",
        "mixer-drive-input",
        "mixer-glue",
        "mixer-glue-input",
        "mixer-send",
        "mixer-send-input",
        "Cut {percentLabel(channel.lowCut)}",
        "Air {percentLabel(channel.air)}",
        "Drive {percentLabel(channel.drive)}",
        "Glue {percentLabel(channel.glue)}",
        "Space {percentLabel(channel.send)}",
        "StemLevelMeter",
        "analyzeStemExports",
        "stemAnalyses",
        "isStemTrackId",
        "stem-level-meter-${trackId}",
        "stem-peak-db-${trackId}",
        "stem-rms-db-${trackId}",
        "stem-headroom-db-${trackId}",
        "MixCoach",
        "MixCoachCheck",
        "createMixCoachChecks",
        "masterHeadroomCheck",
        "limiterCheck",
        "stemBalanceCheck",
        "lowEndBlendCheck",
        "mixCoachSummary",
        "mix-coach",
        "mix-coach-summary",
        "mix-coach-check-${check.id}",
        "applyMasterPreset",
        "mixer-pan",
        "mixer-pan-input",
        "mixer-solo",
    ],
    "src/audio/scheduler.ts": [
        "scheduleAheadSeconds",
        "startRealtimePlayback",
        "getProject",
        "currentProject",
        "masterGain.gain.setTargetAtTime",
        "scheduleMetronomeClick",
        "metronomeEnabled",
        "PlaybackMode",
        "playbackContextForStep",
        "arrangementContextForBar",
        "arrangementEnergyGain",
        "energyGain",
        "mutedTracks",
        "arrangementTrackMix",
        "onStep",
        "activePattern",
        "chordPitches",
        "SoundDesign",
        "drumStepTimingMs",
        "drumStepVelocity",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "hatRepeatCount",
        "sidechainGainForStep",
        "lowCut",
        "air",
        "drive",
        "glue",
        "channelHighpassHz",
        "channelAirFilterHz",
        "connectChannelGlue",
        "driveCurve",
        "channelMix",
        "createSpaceBus",
        "connectScheduledOutput",
        "createStereoPanner",
    ],
    "src/audio/render.ts": [
        "patternForSlot",
        "arrangementBlock",
        "arrangementBarCount",
        "arrangementBlockForBar",
        "arrangementTotalBars",
        "arrangementEnergyGain",
        "energyGain",
        "arrangementBlockMutesTrack",
        "mutedChannelMix",
        "arrangementChannelMix",
        "createRenderNoiseSeed",
        "seededNoiseSample",
        "hashString",
        "hashNumbers",
        "normalizeArrangementBars",
        "chordPitches",
        "SoundDesign",
        "drumStepTimingMs",
        "drumStepVelocity",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "hatRepeatCount",
        "sidechainGainForStep",
        "lowCut",
        "air",
        "drive",
        "glue",
        "send",
        "spaceSendMix",
        "addToneWithSend",
        "addNoiseWithSend",
        "applySpaceReturn",
        "channelHighpassHz",
        "channelDriveSample",
        "channelGlueSample",
        "toneEqFactor",
        "addTone",
        "channelMix",
        "masterOutputGain",
        "stemTrackIds",
        "StemTrackId",
        "StemExportAnalyses",
        "ExportAnalysis",
        "analyzeExport",
        "analyzeStemExports",
        "exportStems",
        "stemTrackLabel",
    ],
    "src/audio/midi.ts": [
        "createMidiFile",
        "exportMidi",
        "midiFileName",
        "MThd",
        "MTrk",
        "ticksPerQuarter",
        "ticksPerStep",
        "arrangementBlockForBar",
        "arrangementBlockMutesTrack",
        "arrangementEnergyGain",
        "drumStepShouldPlay",
        "hatRepeatCount",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "chordPitches",
        "GrooveForge Drums",
        "GrooveForge 808",
        "GrooveForge Synth",
        "GrooveForge Chords",
        "audio/midi",
    ],
    "src/domain/workstation.ts": [
        "styleProfiles",
        "starterProject",
        "StyleProfile",
        "metronomeEnabled",
        "bassPitchLanes",
        "melodyPitchLanes",
        "scalePitches",
        "retargetPitchNameToKey",
        "retargetPitchToKey",
        "retargetPatternKey",
        "retargetProjectKey",
        "serializeProjectFile",
        "parseProjectFile",
        "PatternData",
        "DrumVelocities",
        "DrumTimings",
        "DrumProbabilities",
        "probability: number",
        "DrumGroovePreset",
        "drumGroovePresetIds",
        "drumGroovePresetLabel",
        "applyDrumGroovePreset",
        "PatternVariationPreset",
        "patternVariationPresetIds",
        "patternVariationPresetLabel",
        "createPatternVariation",
        "drumStepTimingMs",
        "drumStepVelocity",
        "normalizeDrumTimingMs",
        "grooveVelocity",
        "grooveTimingMs",
        "hatRepeatCount",
        "drumStepProbability",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "normalizeDrumProbability",
        "normalizeEventProbability",
        "normalizeDrumVelocity",
        "normalizeHatRepeat",
        "sidechainGainForStep",
        "ChordEvent",
        "chordQualities",
        "ChordInversion",
        "chordInversions",
        "chordInversionLabel",
        "normalizeChordInversion",
        "chordPitches",
        "SoundDesign",
        "soundPresetIds",
        "soundPresetDesign",
        "soundPresetLabel",
        "patternSlots",
        "createStylePatternSet",
        "styleSoundPreset",
        "stylePatternBlueprints",
        "BeatBlueprint",
        "BeatBlueprintId",
        "beatBlueprintIds",
        "beatBlueprints",
        "applyBeatBlueprint",
        "applyBeatBlueprintMixer",
        "createEmptyPatternData",
        "ArrangementSection",
        "ArrangementMuteTrack",
        "ArrangementMovePreset",
        "arrangementMovePresetIds",
        "arrangementMovePresetLabel",
        "arrangementMovePresetLabels",
        "applyArrangementMovePreset",
        "arrangementMuteTrackIds",
        "arrangementMuteTrackLabel",
        "arrangementBlockMutesTrack",
        "normalizeArrangementMutedTracks",
        "arrangementSections",
        "minArrangementBars",
        "maxArrangementBars",
        "normalizeArrangementEnergy",
        "arrangementEnergyGain",
        "normalizeArrangementBars",
        "arrangementTotalBars",
        "masterPresets",
        "masterPresetCeilingDb",
        "normalizeProjectState",
        "MixerChannelInput",
        "normalizeMixerEq",
        "normalizeMixerChannels",
        "lowCut",
        "air",
        "drive",
        "glue",
        "send",
    ],
}


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def check_required_paths(errors: list[str]) -> None:
    for path in REQUIRED_PATHS:
        if not (ROOT / path).exists():
            errors.append(f"missing required path: {path}")


def check_root_markdown(errors: list[str]) -> None:
    allowed = {"README.md", "AGENTS.md"}
    found = {path.name for path in ROOT.glob("*.md")}
    extra = sorted(found - allowed)
    if extra:
        errors.append(f"unexpected root markdown files: {', '.join(extra)}")


def check_forbidden_paths(errors: list[str]) -> None:
    if (ROOT / "docs/plan").exists():
        errors.append("forbidden path exists: docs/plan")


def check_plan_names(errors: list[str]) -> None:
    for directory in [
        ROOT / "docs/exec_plans/active",
        ROOT / "docs/exec_plans/completed",
    ]:
        if not directory.exists():
            continue
        for path in directory.glob("*.md"):
            if not PLAN_RE.fullmatch(path.name):
                errors.append(f"invalid plan filename: {rel(path)}")


def check_text_expectations(errors: list[str]) -> None:
    for file_path, needles in TEXT_EXPECTATIONS.items():
        text = (ROOT / file_path).read_text(encoding="utf-8")
        for needle in needles:
            if needle not in text:
                errors.append(f"{file_path} missing text: {needle}")


def check_official_sources(errors: list[str]) -> None:
    text = (ROOT / "docs/references/official-sources.md").read_text(encoding="utf-8")
    if "| TODO |" in text:
        errors.append("official sources still contain placeholder table rows")


def check_strict_todos(errors: list[str]) -> None:
    ignored_prefixes = {
        ".worktree/",
        "dist/",
        "dist-electron/",
        "harness/templates/",
        "node_modules/",
    }
    for path in ROOT.rglob("*.md"):
        relative = rel(path)
        if any(relative.startswith(prefix) for prefix in ignored_prefixes):
            continue
        text = path.read_text(encoding="utf-8")
        if "TODO" in text:
            errors.append(f"strict mode found TODO in {relative}")


def check_offline_render_determinism(errors: list[str]) -> None:
    render_text = (ROOT / "src/audio/render.ts").read_text(encoding="utf-8")
    if "Math.random" in render_text:
        errors.append("src/audio/render.ts must not use Math.random in the offline render path")


def run_checks(strict: bool = False) -> list[str]:
    errors: list[str] = []
    check_required_paths(errors)
    check_root_markdown(errors)
    check_forbidden_paths(errors)
    check_plan_names(errors)
    check_text_expectations(errors)
    check_official_sources(errors)
    check_offline_render_determinism(errors)
    if strict:
        check_strict_todos(errors)
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate the GrooveForge project base.")
    parser.add_argument("--strict", action="store_true", help="Fail on TODO markers outside templates.")
    args = parser.parse_args(argv)

    errors = run_checks(strict=args.strict)
    if errors:
        print("QA failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    mode = "strict " if args.strict else ""
    print(f"GrooveForge {mode}QA passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
