#!/usr/bin/env python3
"""Validate the GrooveForge project base."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PLAN_RE = re.compile(r"plan-\d{3}-[a-z0-9][a-z0-9-]*\.md$")

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "package.json",
    "index.html",
    "vite.config.ts",
    "tsconfig.json",
    "tsconfig.electron.json",
    "electron/main.ts",
    "electron/preload.ts",
    "src/main.tsx",
    "src/ui/App.tsx",
    "src/audio/midi.ts",
    "src/domain/workstation.ts",
    "src/audio/render.ts",
    "src/audio/scheduler.ts",
    "src/styles.css",
    "docs/architecture/harness.md",
    "docs/architecture/product-architecture.md",
    "docs/product/product.md",
    "docs/quality/rules.md",
    "docs/privacy/principles.md",
    "docs/references/official-sources.md",
    "docs/exec_plans/active",
    "docs/exec_plans/completed",
    "docs/meetings/index.md",
    "docs/reviews",
    "harness/templates/exec-plan.md",
    "harness/templates/meeting.md",
    "harness/templates/review.md",
]

TEXT_EXPECTATIONS = {
    "README.md": [
        "making beats across genres",
        "beat workstation first, not a sampler-first app",
        "directly writing the beat rather than importing or chopping audio",
        "Concept lock: GrooveForge is not a sampling app.",
        "all-genre beat-production mini DAW",
        'In the user\'s terms, it is "비트(모든 장르)를 만드는" app',
        "직접 비트를 작곡하고 사운드를 설계하고 믹싱/마스터링까지 하는 비트 제작 미니 DAW.",
        "Direct composition is the product spine",
        "program drums, 808/bass, melody, chords, FX, and automation as editable musical events",
        "Pattern Programming, Drum Sequencing, 808/Bass Synthesis, Melody/Chord Composition, Sound Design, Arrangement, Mixing, Mastering, and Export.",
        "opening a compact beat-making DAW, not a sample browser",
        "Genre breadth is part of the core, not a future sampling pack.",
        "BPM/key/style -> pattern programming -> drums -> 808/bass -> melody/chords -> sound design -> arrangement -> mixing -> mastering -> export",
        "sample import -> chop/slice -> pitch/stretch -> one-shot or sampler mapping",
        "Sampling is a secondary add-on.",
        "It should enter as an optional sound source or instrument layer inside the beat workstation",
        "A complete GrooveForge beat must be possible with no imported audio.",
        "If a draft, screen, or roadmap has to choose what appears first, the answer is direct beat creation",
        "Sampling placement rule: the default empty project, first visible actions, MVP proof, primary navigation, and new plan titles must lead with editable musical events and beat-making controls.",
        "Keep first-run UI and default navigation focused on making beats across genres",
        "Treat sample-free beat creation as the proof of the product",
        "Keep default screens, plan titles, and roadmap ordering anchored to editable musical events",
        "local project save/load",
        "Key changes that retarget Pattern A/B/C 808, synth, and chord-root event data",
        "Style selector that applies editable genre groove templates for Trap, Drill, Boom Bap, Lo-fi, House, R&B, Jersey Club, Phonk, Garage, and Experimental",
        "Style Inspector with Style Quick Picks that explain and apply each genre's BPM range, active/default swing, bass role, melody role, sound preset, and Pattern A/B/C event density from local project data.",
        "Key Compass for local read-only scale notes, chord motion, 808/bass posture, melody posture, and selected-note or selected-chord focus so beginners can compose inside the key and producers can scan harmony quickly.",
        "Groove Compass for local read-only selected-pattern drum density, kick/clap anchors, hat motion, timing feel, chance posture, and selected drum focus so beginners can understand groove foundations and producers can scan pocket quickly.",
        "Composer Guide for local read-only drums, 808/bass, harmony, melody, arrangement, and finish posture so beginners know the next writing focus and producers can scan missing layers quickly.",
        "Style-aware Composer Actions for explicit local writing moves with inline scope, impact, and undo previews plus a post-click local result strip showing updated beat metrics, audition cues, and next checks, routing Composer Guide focus into existing undoable Drum Foundation, 808 Bassline, Chord Progression, Melody Motif, Pattern Fill, Pattern Chain, arrangement template, and Master Finish paths without sampling or hidden generation.",
        "Beat Blueprints for sample-free project starts that apply style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset while staying fully editable.",
        "drum velocity, Drum Foundation Pads for one-click kick/clap/hat/perc foundations, Drum Accent Pads, event chance, chance badges, microtiming, one-click groove humanization, hat repeat dynamics, 808 Bassline Pads, 808 Glide Pads for one-click length/glide/chance shaping, 808 Contour Pads for bassline direction shaping, Desktop Keyboard Capture for scale-locked 808/Synth note entry, Melody Motif Pads, Melody Accent Pads, Melody Contour Pads for one-click Synth phrase direction/velocity/chance shaping, and selected-note move/transpose/duplicate tools",
        "Desktop Keyboard Capture for scale-locked 808/Synth note entry",
        "Key-aware chord progression presets with Chord Pads, Chord Rhythm Pads, and Chord Voicing Pads for one-click chord color, inversion, length, velocity, and chance shaping, chord add/delete, selected-chord move/duplicate/inversion tools, and per-chord chance controls",
        "kick-to-808 sidechain ducking",
        "Sound presets, Drum Kit Pads for one-click built-in kick/clap/hat tone posture, Sound Focus Pads, and Studio tone controls for built-in drum, 808, kick-duck sidechain, synth, and chord engines.",
        "Delivery Targets for starter sketch, vocal session, beat-store demo, club demo, and one editable custom outcome, with explicit target alignment for arrangement length, master preset, and mix posture.",
        "Independent Pattern A/B/C variations with Pattern Compare cue/use cards, Pattern Stack Pads for one-click 808/chord/Synth sketches, Drum Foundation Pads for editable rhythm foundations, Groove Feel Pads for editable timing/chance feel, Drum Accent Pads for editable velocity shape, deterministic Subtle/Hook/Break tools, one-click Drum Fill/808 Pickup/Melody Turn tail moves, copy/clear tools, and editable arrangement blocks with Arrangement Arc Pads, Arrangement Focus presets, one-click Drop/Build/Hook Lift moves, per-track mutes, audible energy, bar length, split, merge, duplicate, move, and delete controls",
        "Pattern Chain presets, an 8-step chain editor, and Chain Expand that turn Pattern A/B/C variations into editable arrangement sketches and longer song-form outlines.",
        "Read-only Beat Readiness checks for drums, 808, melody/chords, arrangement, and export completeness.",
        "Beat Passport summary for target, length, Pattern A/B/C use, readiness, export, stems, and master posture from local project/render state.",
        "Production Snapshot for local read-only target, form, Pattern A/B/C coverage, mix, and handoff posture so producers can scan a session fast and beginners can see what matters next.",
        "Finish Checklist for local read-only Compose, Arrange, Mix, Master, and Handoff readiness before export.",
        "Review Queue for local read-only prioritized production issues across composition, arrangement, mix/master, target, and handoff.",
        "Handoff Pack panel that groups explicit WAV, stem, MIDI, and Handoff Sheet export actions with local deliverable status.",
        "Beat Map production overview that uses the selected fixed or custom Delivery Target to show beginner workflow stages, producer-facing song/pattern/mix/stem metrics, and explicit local action buttons from the current project state.",
        "Structure Lens panel that checks target fit, section coverage, hook contrast, and energy arc from the current arrangement with explicit local arrangement actions.",
        "Song Form Overview for a compact visual map of sections, Pattern A/B/C usage, bar ranges, energy, muted tracks, and selected arrangement block navigation.",
        "Next Move strip that turns readiness/export state into explicit local actions such as Blueprint, target alignment, Pattern Compare, Pattern Fill, Pattern Chain, Hook Lift, Master Finish, Save Slot, and Mix Check, then shows post-click local result metrics, audition cues, and next checks.",
        "Arrangement templates for 8-bar loop, full beat, hook-first, and breakdown song structures with explicit section lengths, plus Arrangement Arc Pads for one-click full-song energy shaping.",
        "Desktop editing shortcuts, Keyboard Capture, and Quick Actions command search for arrangement playback, Pattern A/B/C switching, selected event deletion, save, open, undo, redo, snapshots, blueprints, pattern fills, Arrangement Focus, mix fixes, master finish, and export, with post-run local result metrics, audition cues, and next checks after explicit command clicks.",
        "Undo/redo edit history",
        "Project Snapshots for local idea slots that can save, rename, restore, and delete beat states inside the project file.",
        "Snapshot Compare for local read-only comparison of the current beat against saved snapshots by setup, length, readiness, export, stems, and master posture.",
        "Realtime transport loop controls for Song, selected Block, and Pattern audition",
        "metronome toggle with accented downbeat clicks",
        "Live playback that follows future pattern, arrangement track mutes, BPM, mixer, sound, and master edits without forcing users to stop and restart.",
        "Arrangement Arc Pads, Arrangement Focus presets, one-click Drop/Build/Hook Lift moves, per-track mutes, per-block bar lengths, split/merge controls, and audible energy",
        "Basic mixer volume/pan/mute/solo, Stem Audition Pads for Full Mix/Drums/808/Synth/Chords solo checks, Mix Balance Pads for one-click editable rough balance, channel low-cut/air EQ, Drive/Glue mix controls, Space send FX",
        "deterministic Mix Coach checks with explicit Mix Fix actions",
        "Master Finish Pads for editable demo/vocal/store/club output posture",
        "per-stem export level meters",
        "deterministic Mix Coach checks with explicit Headroom/Stem Balance/Low End Mix Fix actions",
        "Master Finish Pads, master preset ceiling",
        "arrangement MIDI export for DAW handoff",
        "reproducible export peak/RMS/headroom meter",
        "transport with arrangement playback, Pattern preview, Song/Block/Pattern loop audition, and a realtime-only metronome",
        "Keyboard Capture for 808/Synth note entry",
        "Quick Actions command search with Master Finish actions and post-run local result feedback",
        "Project Snapshots",
        "Snapshot Compare",
        "Beat Blueprints for sample-free editable project starts",
        "Key Compass for scale/chord/bass/melody focus",
        "Groove Compass for selected-pattern rhythm/pocket focus",
        "Composer Guide for composition-stage writing focus",
        "style-aware Composer Actions for explicit local writing moves with scope/impact/undo previews plus post-click updated-metric, audition-cue, and next-check result feedback",
        "Delivery Targets for starter sketch, vocal session, beat-store demo, club demo, and custom outcomes",
        "local Next Move actions that can align the selected target, suggest Pattern Chain when arrangement structure is weak, or apply Master Finish with post-click result-metric, audition-cue, and next-check feedback",
        "Pattern Compare cue/use cards",
        "Pattern Stack Pads for editable 808/chord/Synth sketches",
        "Drum Foundation Pads for editable kick/clap/hat/perc foundations",
        "Groove Feel Pads for editable timing/chance feel",
        "Drum Accent Pads for editable velocity shape",
        "deterministic Pattern variation tools",
        "Pattern Fill tail moves",
        "editable scale-aware 808/melody lanes with 808 Bassline Pads, 808 Glide Pads, 808 Contour Pads, Melody Motif Pads, Melody Accent Pads, Melody Contour Pads, note chance badges, and selected-note move/transpose/duplicate tools",
        "mixer volume/pan/mute/solo, Stem Audition Pads for Full Mix/Drums/808/Synth/Chords solo checks, Mix Balance Pads, channel low-cut/air EQ",
        "Drive/Glue mix controls",
        "chord progression presets plus Chord Pads, Chord Rhythm Pads, Chord Voicing Pads, add/delete/selected-chord move/duplicate/inversion/chance controls",
        "sound design presets, Drum Kit Pads for built-in drum tone posture, Sound Focus Pads, Studio tone controls",
        "read-only Beat Passport, Production Snapshot, Finish Checklist, Review Queue, and Beat Readiness checks",
        "Handoff Pack export surface",
        "Structure Lens arrangement fit/section/hook/energy checks",
        "Song Form Overview for full-song section/pattern/energy navigation",
        "Session Brief for bounded local artist, vibe, reference, and handoff notes stored in the project file.",
        "Session Brief for local artist/vibe/reference/handoff notes",
        "target-aware Beat Map workflow and producer metrics",
        "local Next Move actions that can align the selected target, suggest Pattern Chain when arrangement structure is weak, or apply Master Finish with post-click result-metric, audition-cue, and next-check feedback",
        "Pattern Chain 8-bar sketches with per-step A/B/C cycling plus Chain Expand song-form outlining",
        "Space send FX",
        "per-stem export level meters",
        "deterministic Mix Coach checks",
        "reproducible export peak/RMS/headroom meter",
        "one-click stem export",
        "arrangement MIDI export",
        "Local Handoff Sheet text export that summarizes title, BPM/key/style, Delivery Target, Session Brief, arrangement, export meter, and stem meter data for collaboration and review.",
        "Handoff Sheet text export",
        "npm run desktop",
    ],
    "AGENTS.md": [
        "No Exec Plan, No Work",
        "GrooveForge is an all-genre, event-based beat workstation",
        "First-run UI, default navigation, and roadmap order should lead with direct beat composition",
    ],
    "docs/product/product.md": [
        "It is beat-first, not sampler-first.",
        "directly writing the beat rather than importing or chopping audio",
        "Corrected concept: GrooveForge is a beat-production mini DAW",
        'In the user\'s terms, it is "비트(모든 장르)를 만드는" app',
        "직접 비트를 작곡하고 사운드를 설계하고 믹싱/마스터링까지 하는 비트 제작 미니 DAW.",
        "It can support sampling later, but sampling is not the project identity, first-run workflow, MVP proof, or core architecture.",
        "The center is making a beat directly, not finding a sample to start from.",
        "Pattern Programming, Drum Sequencing, 808/Bass Synthesis, Melody/Chord Composition, Sound Design, Arrangement, Mixing, Mastering, and Export.",
        "The product draft should be read in this order whenever there is ambiguity: all-genre beat creation first",
        "Pattern programming for all supported styles.",
        "Optional sampling module, later and outside the MVP:",
        "audio sample import -> chop/slice -> pitch/stretch -> one-shot or sampler mapping",
        "No user should need a sample to make the first complete beat.",
        "When sampling appears later, it should behave like an optional sound source or instrument layer inside the beat workstation",
        "Sampling placement rule: the default empty project, first visible actions, MVP proof, primary navigation, onboarding language, and plan titles must start from editable musical events and beat-making controls.",
        "This loop is the product spine for all supported genres.",
        "샘플 없이도 8마디 비트를 만들고 WAV로 export할 수 있어야 한다.",
        "This sentence supersedes any sampling-first interpretation of the brief.",
        "Sampling can be useful, but it must stay behind the composition engine",
        "Primary navigation and the first empty project should expose beat-making controls before sample workflows",
        "Sampling entry points, when added, should be opt-in secondary paths",
        "Any future sampler UI should be framed as an additional instrument or sound-source lane after direct composition exists",
        "The core model centers on editable musical events, not audio clips or a sampler asset graph",
        "it means a pattern, MIDI, or automation container",
        "Local project save/load",
        "Key changes retarget Pattern A/B/C 808/bass, melody, and chord-root musical events",
        "Style selector that applies key-aware editable groove templates for Trap, Drill, Boom Bap, Lo-fi, House, R&B, Jersey Club, Phonk, Garage, and Experimental",
        "Style Inspector with Style Quick Picks that derive read-only BPM range, active/default swing, bass role, melody role, sound preset, and Pattern A/B/C event density from local style/profile/project data while applying styles through the existing undoable style-selection path.",
        "Key Compass derived from local key, selected Pattern A/B/C chord events, 808/bass notes, melody notes, selected note, and selected chord state so beginners can see safe scale notes and focus degrees while producers can inspect harmonic posture without changing the beat.",
        "Groove Compass derived from local selected Pattern A/B/C drum pattern, velocity, microtiming, probability, and hat repeat data so beginners can understand drum foundation and producers can inspect pocket without changing the beat.",
        "Composer Guide derived from local selected Pattern A/B/C drum hits, 808/bass notes, chord events, melody notes, arrangement length, Delivery Target, deterministic export analysis, and deterministic stem analysis so beginners can identify the next writing focus while producers can scan composition gaps without changing the beat.",
        "Composer Actions derived from local Composer Guide, selected style profile, Beat Readiness, Delivery Target, deterministic export analysis, and deterministic stem analysis state so users can preview scope, impact, and undo posture before explicitly clicking style-prioritized writing moves for drums, 808/bass, harmony, melody, arrangement, and finish flow through existing undoable handlers, then read a UI-only local result strip with updated metrics, audition cues, and next checks without hidden generation.",
        "Beat blueprints: sample-free editable project starts that combine style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset.",
        "Delivery Targets: local starter sketch, vocal session, beat-store demo, club demo, and editable custom targets that can be set without changing the beat or explicitly aligned to arrangement length, master preset, and mix posture.",
        "Session Brief: bounded local artist, vibe, reference, and notes fields stored in the project file for beat intent and handoff context.",
        "Groove Compass: local read-only selected-pattern drum density, kick/clap anchor, hat motion, timing feel, probability, and selected drum focus summary so beginners can understand groove foundations and producers can scan pocket quickly.",
        "Composer Guide: local read-only drums, 808/bass, harmony, melody, arrangement, and finish posture summary so beginners can see the next writing focus and producers can scan missing layers quickly.",
        "Composer Actions: style-aware explicit local writing move buttons derived from Composer Guide posture, selected style profile, and local project state, with inline scope, impact, and undo previews before each user-clicked action routes through existing undoable Drum Foundation, 808 Bassline, Chord Progression, Melody Motif, Pattern Fill, Pattern Chain, arrangement template, and Master Finish handlers, then shows a UI-only local result strip with updated beat metrics, audition cues, and next checks.",
        "Instrument panel: drum kit, synth 808, simple synth, chord synth, effects, Drum Kit Pads for built-in drum tone posture, Sound Focus Pads, and sound-design controls.",
        "Beat Blueprints that apply complete sample-free project starts across style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset while preserving manual editing.",
        "Desktop Keyboard Capture for scale-locked 808/Synth note entry",
        "editable drum velocity, Drum Foundation Pads, Drum Accent Pads, probability, visible chance badges, microtiming, one-click groove humanization, and hat repeat dynamics",
        "808 Bassline Pads, 808 Glide Pads, 808 Contour Pads, Desktop Keyboard Capture, mono mode, glide, note chance badges, selected-note move/transpose/duplicate tools, saturation direction, and kick-to-808 sidechain ducking",
        "kick-to-808 sidechain ducking",
        "sidechain ducking",
        "Sound design presets, Drum Kit Pads for one-click built-in kick/clap/hat tone posture, Sound Focus Pads, and Studio tone controls for kick punch, snare snap, hat brightness, 808 drive/decay, sidechain ducking, synth brightness/release, and chord warmth/width.",
        "editable step/root/quality/inversion/length/velocity/chance, visible chance badges, add/delete controls, and selected-chord move/duplicate/inversion tools",
        "Pattern editor: drum step sequencer with Drum Foundation Pads for one-click kick/clap/hat/perc foundations, bass grid with 808 Bassline Pads, 808 Glide Pads for one-click length/glide/chance shaping, and 808 Contour Pads for bassline direction shaping, chord progression with key-aware Chord Pads, Chord Rhythm Pads, and Chord Voicing Pads for one-click chord color/inversion/shape changes, melody grid with Melody Motif Pads, Melody Accent Pads, and Melody Contour Pads for one-click Synth phrase direction/velocity/chance shaping, Pattern Stack Pads for one-click 808/chord/Synth sketches, Groove Feel Pads for editable timing/chance feel, Drum Accent Pads for editable velocity shape, Desktop Keyboard Capture for scale-locked 808/Synth note entry, Pattern Compare cue/use cards, variation A/B/C, and one-click Pattern Fill tail moves.",
        "Independent Pattern A/B/C storage with Pattern Compare cue/use cards for density and arrangement-use decisions, Pattern Stack Pads for one-click 808/chord/Synth sketches, Drum Foundation Pads for editable rhythm foundations, Groove Feel Pads for editable timing/chance feel, Drum Accent Pads for editable velocity shape, deterministic Subtle/Hook/Break variation tools, one-click Drum Fill/808 Pickup/Melody Turn/Clear Tail moves, plus copy/clear tools for drum, bass, chord, and melody variations",
        "Read-only Beat Readiness checks for drums, 808/bass, melody/chords, arrangement structure, and export signal status.",
        "Delivery Targets stored in project state with safe migration for older files; setting a fixed or custom target changes only the target, editable custom fields stay bounded in local project data, and explicit target alignment can update arrangement template, master preset, master ceiling, and mix posture through undoable project history.",
        "Session Brief stored in local project state with bounded artist, vibe, reference, and notes text so beginners can clarify intent and producers can keep handoff context without media uploads or cloud collaboration.",
        "Beat Passport summary derived from local project state, Beat Readiness, export analysis, stem analysis, Delivery Target, and master posture so beginners and producers can scan target, length, Pattern A/B/C use, readiness, export, stems, and master state without changing the beat.",
        "Production Snapshot derived from local project state, Beat Readiness, arrangement blocks, Pattern A/B/C event data, deterministic export analysis, deterministic stem analysis, selected Delivery Target, Mix Coach checks, and Session Brief so producers can scan target, form, patterns, mix, and handoff posture while beginners see what matters next without changing the beat.",
        "Finish Checklist derived from local project state, Beat Readiness, Structure Lens posture, Mix Coach checks, export analysis, stem analysis, Delivery Target, and Session Brief so users can review Compose, Arrange, Mix, Master, and Handoff readiness without changing the beat.",
        "Review Queue derived from local project state, Beat Readiness, Structure Lens signals, Mix Coach checks, export analysis, stem analysis, Delivery Target, and Session Brief so users can scan the top production issues without changing the beat.",
        "Handoff Pack surface that groups explicit full-mix WAV, stem WAV, arrangement MIDI, and Handoff Sheet export actions with status derived from local project state and deterministic export/stem analysis.",
        "Beat Map production overview derived from local project, selected fixed or custom Delivery Target, Beat Readiness, export analysis, and stem analysis state, showing beginner workflow stages, producer-facing song/pattern/export/stem metrics, and explicit local action buttons without mutating project state unless clicked.",
        "Structure Lens derived from local arrangement blocks and selected Delivery Target, showing target fit, section coverage, hook contrast, and energy arc while routing explicit action buttons through existing undoable arrangement paths.",
        "Song Form Overview derived from local arrangement blocks and Pattern A/B/C event data, showing section flow, pattern usage, selected block, energy range, per-block bar spans, muted tracks, and navigation buttons that select existing arrangement blocks without creating undo history or mutating arrangement data.",
        "Next Move strip that gives one primary recommended action and secondary local actions from the current readiness/export state, including target alignment, Pattern Compare, Pattern Chain when arrangement structure is weak, and Master Finish when export posture needs a final target, then shows UI-only local result metrics, audition cues, and next checks after explicit clicks without mutating Beat Readiness.",
        "Beat Map: deterministic production overview that maps the current beat into Start, Compose, Arrange, Polish, and Deliver stages against the selected fixed or custom Delivery Target, plus song length, Pattern A/B/C usage, export, and stem metrics for faster beginner and producer decisions.",
        "Song Form Overview: compact visual arrangement map for section flow, Pattern A/B/C usage, bar ranges, energy, muted-track posture, and selected-block navigation without rewriting arrangement data.",
        "Quick Actions: searchable local command palette for transport, project, creative, arrangement, mix, master finish, and export actions, with a UI-only post-run result strip that shows command status, one local metric, audition cue, and next check.",
        "Stem Audition Pads that explicitly set Full Mix/Drums/808/Synth/Chords audition through existing mixer solo/mute state",
        "Undo/redo edit history for project-level pattern, arrangement, mixer, sound, and master changes",
        "Project snapshots: local idea slots for saving, renaming, restoring, and deleting beat states inside the project file.",
        "Snapshot Compare: local read-only comparison of the current beat against saved Project Snapshots by setup, arrangement length, readiness, export, stems, and master posture.",
        "Project Snapshots that save, rename, restore, and delete local beat idea states inside the `.grooveforge.json` file without cloud sync or nested snapshot recursion.",
        "Snapshot Compare derived from local current project state and saved Project Snapshot payloads so users can compare setup, arrangement length, readiness, export, stems, and master posture without restoring, deleting, renaming, saving, or mutating the beat.",
        "Desktop editing shortcuts, Keyboard Capture, and Quick Actions command search for arrangement playback, Pattern A/B/C selection, selected drum/note deletion, save, open, undo, redo, snapshots, blueprints, pattern fills, Arrangement Focus, mix fixes, master finish, and export while leaving focused inputs alone, then showing UI-only local result metrics, audition cues, and next checks after explicit command clicks.",
        "Transport playback modes for full arrangement playback by default, selected-block loop audition, and fast selected-pattern preview while editing.",
        "Realtime metronome toggle with accented downbeat clicks",
        "without adding click audio to WAV or stem export",
        "Live playback reads the current project while scheduling future steps",
        "selected-pattern preview, arrangement block edits, arrangement track mutes, arrangement length, arrangement energy, BPM, mixer, sound, and master changes can be heard without stopping and restarting",
        "Chord progression track with scale-locked roots, key-aware Chord Pads, Chord Rhythm Pads, Chord Voicing Pads, key-aware progression presets",
        "editable step/root/quality/inversion/length/velocity/chance, visible chance badges, add/delete controls, and selected-chord move/duplicate/inversion tools",
        "Simple synth melody track with editable scale-aware grid, Melody Motif Pads, Melody Accent Pads, Melody Contour Pads, Desktop Keyboard Capture, velocity control, note chance badges, and selected-note move/transpose/duplicate tools.",
        "Sound design presets, Drum Kit Pads for one-click built-in kick/clap/hat tone posture, Sound Focus Pads, and Studio tone controls",
        "Editable arrangement blocks and templates",
        "Arrangement Arc Pads for one-click full-song energy/section posture",
        "Arrangement Focus presets",
        "Pattern Chain presets, per-step A/B/C cycling, and Chain Expand song-form outlining that edit only arrangement block assignments while preserving Pattern A/B/C musical event data, mixer state, sound design, master state, and existing export paths.",
        "one-click Drop/Build/Hook Lift moves",
        "8-bar loop, full beat, hook-first, and breakdown structures",
        "per-block track mutes",
        "audible per-block energy",
        "per-block bar length",
        "split/merge controls",
        "duplicate, move, and delete controls",
        "Mixer volume, pan, mute, solo, Stem Audition Pads that explicitly set Full Mix/Drums/808/Synth/Chords audition through existing mixer solo/mute state, Mix Balance Pads, low-cut/air EQ, Drive/Glue mix controls, built-in Space send FX, per-stem export level meters, deterministic Mix Coach checks, explicit Headroom/Stem Balance/Low End Mix Fix actions, and Master Finish Pads reflected in deterministic render feedback",
        "Master preset ceiling, Master Finish Pads, and output gain.",
        "channel low-cut/air EQ",
        "Drive/Glue mix controls",
        "per-stem export level meters",
        "deterministic Mix Coach checks",
        "Reproducible export peak/RMS/headroom meter with limiter activity status",
        "WAV export through deterministic offline rendering",
        "Stem export through deterministic offline rendering",
        "MIDI export as a deterministic Standard MIDI File with drum, 808, synth, and chord tracks from the current arrangement.",
        "Handoff Sheet export as a local plain text summary of title, BPM/key/style, Delivery Target, Session Brief, arrangement blocks, export meter, and stem meter data without media upload or compliance claims.",
        "Feature priority follows the beat-workstation core:",
        "P3 | sampling and plugin hosting",
    ],
    "docs/quality/rules.md": [
        "QA and review are separate loops.",
        "python3 harness/scripts/run_quality_gate.py",
        "Metronome work must keep click playback realtime-only",
        "keep WAV/stem exports free of metronome audio",
        "Drum probability work must migrate old patterns to 100% chance",
        "808, melody, and chord chance work must migrate older musical events to 100% chance",
        "Chance badge work must keep badges read-only",
        "use deterministic probability gates so exported audio is reproducible",
        "Project file work must reject invalid imports",
        "preserve edited drum, bass, chord, melody, sound design",
        "Project Snapshot work must store snapshots as local project-file data",
        "Snapshot Compare work must derive current-vs-saved snapshot comparison only from local project state",
        "remain read-only; avoid restoring, deleting, renaming, saving, mutating snapshots, triggering exports, or changing recommendations",
        "Song Form Overview work must derive section flow, Pattern A/B/C usage, selected block, energy range, bar spans, muted-track posture, and segment tones only from local arrangement blocks",
        "route segment clicks only through existing selected-block navigation without creating undo history or mutating arrangement",
        "keep snapshot payloads free of nested snapshots",
        "allow save/rename/restore/delete without cloud sync or accounts",
        "keep snapshot names bounded and normalized",
        "Drum dynamics work must migrate old patterns",
        "Drum microtiming work must migrate old patterns",
        "Groove humanize work must be deterministic",
        "Style groove work must apply key-aware editable Pattern A/B/C event data",
        "Style expansion work must add new genres as first-class `StyleId` entries",
        "every new style must remain editable, undoable through the existing style-selection path, sample-free",
        "Style Inspector and Style Quick Picks work must derive read-only BPM range, active/default swing, bass role, melody role, sound preset, and Pattern A/B/C event density",
        "keep style selection accessible/testable",
        "route quick-pick style changes through the existing undoable style-selection path",
        "Key Compass work must derive scale notes, chord motion, 808/bass posture, melody posture, and selected-note or selected-chord focus only from local key",
        "Groove Compass work must derive selected-pattern drum density, kick/clap anchor, hat motion, timing feel, chance posture, and selected drum focus only from local Pattern A/B/C drum pattern, velocity, microtiming, probability, and hat repeat data",
        "Composer Guide work must derive drums, 808/bass, harmony, melody, arrangement, and finish posture only from local selected Pattern A/B/C event data, arrangement blocks, selected Delivery Target, Beat Readiness, deterministic export analysis, and deterministic stem analysis",
        "Composer Actions work must derive action buttons, style priorities, thresholds, copy, scope previews, impact previews, undo posture, post-click result metrics, audition cues, and next checks only from local selected Pattern A/B/C event data, Composer Guide posture, selected style profile, Beat Readiness, arrangement blocks, selected Delivery Target, deterministic export analysis, deterministic stem analysis, current master state, and explicit local preset definitions",
        "keep previews, result strips, audition cues, and next checks informational rather than modal confirmations, autoplay, or export triggers",
        "keep result strips UI-only and out of saved project data",
        "route mutating buttons only through existing undoable Drum Foundation, 808 Bassline, Chord Progression, Melody Motif, Pattern Fill, Pattern Chain, arrangement template, Beat Blueprint, and Master Finish handlers",
        "Beat Blueprint work must apply deterministic sample-free project starts from local style, key, BPM, Pattern A/B/C event data, arrangement templates, sound presets, mixer balance, and master presets",
        "keep the result fully editable and undoable",
        "Sound Focus Pad work must derive kick, drum, 808, sidechain, synth, and chord tone changes from explicit local tone-posture presets",
        "update only editable `SoundDesign` state through undoable project history",
        "Drum Kit Pad work must derive built-in kick, clap, and hat tone posture plus `drum_rack` channel mix from explicit local kit presets",
        "update only editable `SoundDesign` drum parameters and the `drum_rack` mixer channel through undoable project history",
        "Arrangement Arc Pad work must derive full-song section, Pattern A/B/C assignment, bar length, energy, and muted-track posture from explicit local arc presets",
        "update only existing arrangement block fields through undoable project history",
        "Key retarget work must update Pattern A/B/C 808/bass note pitches, melody note pitches, and chord roots by scale degree",
        "Chord progression work must preserve Pattern A/B/C independence",
        "Chord Pad work must derive pad roots and qualities from the current key",
        "Chord Rhythm Pad work must derive chord length, velocity, and chance changes from explicit local rhythm presets",
        "Chord Voicing Pad work must derive chord quality, inversion, length, velocity, and chance changes from explicit local voicing presets",
        "update only the selected Pattern A/B/C chord event through existing undoable chord update paths",
        "keep chord roots and progression presets scale-aware by default",
        "keep add/delete operations undoable",
        "preserve at least one chord event in guided editing",
        "Chord inversion work must migrate older chord events to root position",
        "Selected chord edit tool work must keep chord move, duplicate, delete, and inversion actions scoped to the selected Pattern A/B/C slot",
        "avoid overlapping duplicate or moved chord starts at the same step",
        "Sound design work must keep tone parameters in project state",
        "Sidechain work must keep kick-to-808 ducking",
        "Export meter work must label measurements honestly as peak, RMS, headroom, and limiter activity",
        "Render noise work must keep offline WAV export, stem export, and export meter analysis deterministic from render-relevant project data",
        "avoid `Math.random()` in the offline render path",
        "Stem export work must render isolated drum, 808, synth, and chord WAV files",
        "Stem level meter work must derive drum, 808, synth, and chord meter values from the deterministic offline stem render path",
        "show peak/RMS/headroom honestly without LUFS or true-peak claims",
        "Mix Coach work must derive suggestions only from deterministic full-mix and stem export analysis",
        "communicate peak/RMS/headroom/limiter/stem-balance checks without LUFS, true-peak, platform compliance, or mastering-fix claims",
        "Mix Fix work must run only after explicit user button clicks",
        "Master Finish Pad work must derive master preset, ceiling, and master output gain from explicit local demo, vocal, store, and club posture presets",
        "update only editable master state and the master mixer channel volume through undoable project history",
        "Mix Balance Pad work must derive mixer channel volume, pan, low-cut, air, Drive/Glue, and Space send changes from explicit local rough-balance presets",
        "route all mixer/master changes through undoable project update paths",
        "keep fixes limited to editable mixer/master state",
        "MIDI export work must write deterministic Standard MIDI Files from editable project events",
        "Handoff Sheet export work must write a local plain text summary only after an explicit user click",
        "Pattern work must keep Pattern A/B/C as independent editable event data",
        "Pattern Compare work must derive event, track, and arrangement-use summaries from local Pattern A/B/C and arrangement state",
        "Cue must switch only selected-pattern preview state without autoplay or undo history",
        "Use must route selected-block pattern changes through existing undoable arrangement updates",
        "Copy and clear tools must operate on the selected pattern slot",
        "Pattern preview playback should loop the selected pattern",
        "arrangement playback and WAV export should follow arrangement pattern assignments",
        "Pattern variation work must be deterministic",
        "operate only on the selected Pattern A/B/C slot through undoable project history",
        "keep generated drums, bass, melody, chords, velocities, timings, repeats, and probabilities manually editable",
        "Pattern Stack Pad work must derive 808/bass notes, chord events, and Synth melody notes from the current key after an explicit click",
        "Groove Feel Pad work must derive drum timing, drum chance, note chance, and chord chance changes from explicit local feel presets",
        "Drum Foundation Pad work must derive selected Pattern A/B/C kick, clap, hat, and perc foundations from explicit local rhythm presets",
        "update only selected Pattern A/B/C drum pattern, velocity, timing, probability, and hat repeat data",
        "Drum Accent Pad work must derive drum velocity changes from explicit local accent presets",
        "Pattern Fill work must be deterministic",
        "keep Drum Fill/808 Pickup/Melody Turn/Clear Tail results manually editable",
        "808 Bassline Pad work must derive 808/bass notes from the current key after an explicit click",
        "808 Glide Pad work must derive 808/bass note length, glide, and chance changes from explicit local movement presets",
        "808 Contour Pad work must derive 808/bass pitch direction changes from explicit local contour presets",
        "keep bass note counts, step positions, lengths, glide flags, and chance values stable",
        "Melody Motif Pad work must derive Synth melody notes from the current key after an explicit click",
        "Melody Accent Pad work must derive Synth melody velocity and chance changes from explicit local accent presets",
        "Melody Contour Pad work must derive Synth melody pitch contour, length, velocity, and chance changes from explicit local contour presets",
        "preserve melody note counts and step positions",
        "Delivery Target work must store the selected fixed or custom target in local project state",
        "bounded default custom target",
        "keep target selection and custom target editing separate from target alignment",
        "Session Brief work must store bounded artist, vibe, reference, and notes text in local project state",
        "Beat Readiness work must derive checks from editable Pattern A/B/C, arrangement, and deterministic export analysis data",
        "Beat Passport work must derive compact target, length, Pattern A/B/C, readiness, export, stem, and master posture summaries only from local project state",
        "Production Snapshot work must derive target fit, song form, Pattern A/B/C coverage, mix posture, and handoff posture only from local project state",
        "Finish Checklist work must derive Compose, Arrange, Mix, Master, and Handoff readiness only from local project state",
        "Review Queue work must derive prioritized production issues only from local project state",
        "remain read-only; avoid mutating project state, triggering exports, auto-fixing, or changing recommendations",
        "remain read-only; avoid mutating project state, triggering exports, or changing recommendations",
        "remain read-only, avoid mutating project state or generating musical events",
        "Beat Map work must derive workflow stages, song/pattern metrics, Session Brief status, export state, stem state, and action suggestions only from local project state, selected Delivery Target",
        "Next Move work must derive deterministic recommendations, post-click result metrics, audition cues, and next checks from local project, Beat Readiness, export analysis, selected Delivery Target, arrangement blocks, snapshots, and explicit action definitions",
        "keep result strips UI-only and informational rather than modal confirmations, autoplay, auto-save, or export triggers",
        "Next Move Pattern Chain work must recommend Pattern Chain only from local readiness state",
        "Finish Move Action work must route Master Finish recommendations and Quick Actions through existing `applyMasterFinishPad`",
        "update only master state and master mixer volume",
        "Stem Audition Pad work must derive Full Mix/Drums/808/Synth/Chords audition states from explicit local pad definitions",
        "update only existing mixer `solo` and `muted` fields through undoable project history",
        "keep Full Beat available as an explicit alternative when arrangement structure is weak",
        "run only after explicit user button clicks",
        "route mutating actions through undoable project update paths",
        "Selected note edit tool work must keep 808 and Synth note move, transpose, octave, and duplicate actions scoped to the selected Pattern A/B/C slot",
        "preserve length/glide/velocity/chance fields",
        "avoid overlapping duplicate notes at the same step and pitch",
        "Arrangement editor work must let users change a block's section",
        "bar length, and energy",
        "Arrangement track mute work must migrate older arrangement blocks to no muted tracks",
        "keep mutes scoped to the selected block without mutating Pattern A/B/C events",
        "apply the same mute decisions to realtime arrangement playback, full-mix WAV export, and stem export",
        "Arrangement structure work must preserve at least one block",
        "Arrangement split work must split only the selected arrangement block",
        "preserve total arrangement bars",
        "Arrangement merge work must merge only the selected block with the next block",
        "keep the selected block's section",
        "Arrangement template work must replace only arrangement blocks",
        "align the selected pattern with the first template block",
        "make WAV/stem export follow the applied template length",
        "Pattern Chain work must replace only arrangement blocks with deterministic Pattern A/B/C sequences",
        "Pattern Chain step editor work must cycle only arrangement block Pattern A/B/C assignments through existing undoable project update paths",
        "keep each block's section, bars, energy, muted tracks, and Pattern A/B/C musical event data intact",
        "Pattern Chain expand work must transform only arrangement blocks into a longer deterministic song-form outline",
        "make realtime playback plus WAV/stem/MIDI export follow the chain",
        "Arrangement length work must keep per-block bar counts bounded",
        "migrate older project files without bar counts to one bar per block",
        "make export meter, full-mix WAV export, and stem export follow total arrangement bars",
        "Arrangement playback work must map realtime playback through arrangement blocks",
        "preserving a selected-pattern preview mode",
        "accurate transport status",
        "Transport Loop work must keep Song, selected Block, and Pattern loop scope as explicit local playback state",
        "use selected-block start bar and bar length only for realtime audition",
        "avoid writing loop scope into saved project data",
        "keep WAV/stem/MIDI export plus Handoff Sheet semantics tied to the full arrangement rather than the audition loop",
        "Arrangement energy work must keep Energy as deterministic arrangement-block playback/render interpretation",
        "apply the same gain rule to realtime arrangement playback, WAV export, and stem export",
        "preserve selected-pattern preview at neutral energy",
        "Arrangement Move work must transform only the selected arrangement block's existing energy and mutedTracks state through undoable project history",
        "keep Drop/Build/Hook Lift/Reset deterministic and editable afterward",
        "Arrangement Focus work must derive selected-block summaries from local arrangement and Pattern A/B/C event state",
        "offer only explicit user-clicked Focus presets",
        "update only the selected block's section, Pattern assignment, bar length, energy, and mutedTracks through undoable arrangement paths",
        "Live playback edit work must read current project state while scheduling future steps",
        "already-triggered audio is not rewritten",
        "Undo/redo work must record bounded local project-edit history",
        "keep keyboard shortcuts out of focused inputs",
        "Desktop shortcut work must keep playback, Pattern A/B/C selection, save/open, undo/redo, and selected event deletion scoped to the app window",
        "Keyboard Capture work must route desktop key presses into scale-locked 808 or Synth notes",
        "must route destructive deletion through normal undoable project history",
        "Quick Actions work must remain local and explicit",
        "must derive post-run result status, metrics, audition cues, and next checks only from explicit command metadata and local before/after project state",
        "must keep result strips UI-only and informational rather than modal confirmations, macros, autoplay, auto-save, auto-export, or project data",
        "must keep project/open/save/export actions user-triggered",
        "Handoff Pack work must group WAV, stem, MIDI, and Handoff Sheet deliverables as explicit user-clicked actions routed through existing export handlers",
        "avoid auto-export/background render/downloads",
        "Structure Lens work must derive target fit, section coverage, hook contrast, and energy arc only from local arrangement blocks",
        "route action buttons through existing undoable arrangement, Pattern Chain, target alignment, or Hook Lift paths",
        "Volume, pan, mute, solo, master output gain, and preset ceiling controls",
        "Channel EQ work must keep low-cut/air controls in mixer state",
        "Channel dynamics work must keep Drive/Glue controls in mixer state",
        "FX send work must keep Space/send controls in mixer state",
        "simplified compression honestly",
        "full-mix WAV export, and stem export",
        "sample import, chopping, sampler tracks, or audio warping",
        "Concept correction work must make the all-genre beat-production mini DAW framing explicit",
        "sample import, chopping, pitch/stretch, one-shot mapping, and sampler workflows are optional later paths",
        "Concept correction work must preserve this center list in durable docs",
        'Concept correction work must preserve the user\'s intent that GrooveForge is for "비트(모든 장르)를 만드는" work',
        "Pattern Programming, Drum Sequencing, 808/Bass Synthesis, Melody/Chord Composition, Sound Design, Arrangement, Mixing, Mastering, and Export",
        "First-run UX, default navigation, and roadmap work must lead with direct beat composition",
        "Sampling placement work fails if the default empty project, first visible action, MVP proof, primary navigation, onboarding language, priority table, or plan title makes sample browsing, sample import, chopping, sampler setup, or audio clips appear before editable musical events and beat-making controls.",
        "Sample browsing, chopping, sampler setup, audio clips, and audio warping must stay opt-in optional-sampling paths",
        "core clips are pattern, MIDI, or automation containers",
        "Any product or architecture wording that promotes `AudioClipEvent`, sampler assets, sample browsing, or chopping above editable musical events fails the product boundary",
        "Any future optional-sampling schema must keep `NoteEvent`, `DrumHitEvent`, and automation sufficient for a complete beat",
    ],
    "docs/architecture/product-architecture.md": [
        "The architecture follows a direct-composition pipeline first",
        "Architectural center: Pattern Programming, Drum Sequencing, 808/Bass Synthesis, Melody/Chord Composition, Sound Design, Arrangement, Mixing, Mastering, and Export.",
        "Optional sampling attaches after this pipeline as an additional sound source or instrument layer",
        "Audio import, chopping, stretching, one-shot mapping, and sampler devices are secondary extension paths",
        "Default project creation, first-run navigation, and MVP validation must instantiate editable musical events and built-in instruments first.",
        "Pattern/Event Clips",
        "SessionBrief",
        "bounded local artist, vibe, reference, and notes text for project intent and handoff context",
        "not an imported audio asset",
        "Sampling architecture should attach to the beat workstation",
        "`AudioClipEvent` belongs in that extension layer, not in the core MVP `MusicalEvent` union.",
        "Optional sampling schemas must preserve the existing event-first contract",
        "The core architecture should remain valid with no audio-file entities at all.",
        "Key and scale changes are composition edits over musical event data.",
        "sample browsing, chopping, sampler mapping, and audio warping belong behind explicit optional-sampling entry points",
        "Roadmap and architecture plans should treat `audio` and `sampler` as extension track types until the direct beat workstation is already useful.",
        "Extension track types for optional sampling, later:",
    ],
    "harness/scripts/run_qa.py": [
        '".worktree/"',
    ],
    "docs/references/official-sources.md": [
        "W3C Web Audio API",
        "Electron Docs",
        "Vite Guide",
        "ITU-R BS.1770",
        "Source Gaps",
    ],
    "package.json": [
        "\"desktop\"",
        "\"typecheck\"",
        "\"build\"",
    ],
    "electron/main.ts": [
        "nodeIntegration: false",
        "contextIsolation: true",
        "sandbox: true",
        "grooveforge:save-project",
        "grooveforge:open-project",
    ],
    "electron/preload.ts": [
        "saveProject",
        "openProject",
    ],
    "src/ui/App.tsx": [
        "Guided",
        "Studio",
        "exportMidi",
        "exportWav",
        "exportStems",
        "analyzeExport",
        "ExportMeter",
        "export-meter-status",
        "export-peak-db",
        "export-rms-db",
        "export-headroom-db",
        "export-limiter-percent",
        "master-ceiling",
        "MasterFinishPadId",
        "MasterFinishPadOption",
        "masterFinishPadDefinitions",
        "masterFinishPadOptions",
        "MasterFinishPads",
        "Master Finish",
        '"masterFinish"',
        "onApplyMasterFinish",
        "suggestedMasterFinishPad",
        "masterFinishNextMoveAction",
        "master-finish-${pad.id}",
        "master-finish-pads",
        "startRealtimePlayback",
        "getProject: () => projectRef.current",
        "metronome-toggle",
        "toggleMetronome",
        "PlaybackMode",
        "TransportLoopScope",
        "transportLoopScope",
        "transportLoopMode",
        "transportLoopBars",
        "transportLoopStartBar",
        "transportLoopReadout",
        "selectTransportLoopScope",
        "transportLoopLabel",
        "transportLoopStatus",
        "arrangementStartBar",
        "playbackMode",
        "playback-mode-arrangement",
        "transport-loop-block",
        "playback-mode-pattern",
        "transportPrimary",
        "transportSecondary",
        "currentPatternStep",
        "createStylePatternSet",
        "styleSoundPreset",
        "StyleInspector",
        "style-inspector",
        "style-select",
        "style-quick-picks",
        "style-quick-${profile.id}",
        "onSelectStyle(profile.id)",
        "aria-pressed={selected}",
        "createStyleInspectorSummary",
        "styleDensityLabel",
        "bassStyleRoleLabel",
        "melodyStyleRoleLabel",
        "Applied ${nextStyle.name} groove",
        "BeatBlueprintId",
        "BeatBlueprints",
        "applyBeatBlueprint",
        "applySelectedBeatBlueprint",
        "beatBlueprints",
        "beat-blueprints",
        "beat-blueprint-current",
        "beat-blueprint-${blueprint.id}",
        "retargetProjectKey",
        "applyProjectKey",
        "Retargeted project to ${key}",
        "DrumStepInspector",
        "drum-probability",
        "drum-probability-input",
        "drum-chance-badge-${lane}-${step}",
        "updateSelectedDrumProbability",
        "chance / ${timingLabel",
        "selectedDrumStep",
        "updateSelectedDrumVelocity",
        "updateSelectedHatRepeat",
        "drum-velocity",
        "drum-velocity-input",
        "drum-timing-early",
        "drum-timing-on",
        "drum-timing-late",
        "drum-timing-input",
        "updateSelectedDrumTiming",
        "applySelectedDrumGroove",
        "groove-preset-${preset}",
        "timingLabel",
        "timingBadge",
        "hat-repeat-${repeat}",
        "undoStack",
        "redoStack",
        "undoProject",
        "redoProject",
        "ProjectSnapshot",
        "ProjectSnapshots",
        "saveCurrentSnapshot",
        "restoreSavedSnapshot",
        "deleteSavedSnapshot",
        "commitSnapshotName",
        "snapshotNameDrafts",
        "snapshot-name-${snapshot.id}",
        "handleDesktopShortcut",
        "deleteSelectedEvent",
        "deleteSelectedNote",
        "clearSelectedDrumStep",
        "wantsSave",
        "wantsOpen",
        "event.code === \"Space\"",
        "patternShortcut",
        "undo-button",
        "redo-button",
        "isEditableShortcutTarget",
        "historyLimit",
        "NoteEditor",
        "GrooveFeelId",
        "GrooveFeelOption",
        "grooveFeelDefinitions",
        "grooveFeelOptions",
        "GrooveFeelPads",
        "createGrooveFeelOptions",
        "applyGrooveFeelToPattern",
        "applyGrooveFeel",
        "groove-feel-${feel.id}",
        "groove-feel-pads",
        "DrumAccentId",
        "DrumAccentOption",
        "drumAccentDefinitions",
        "drumAccentOptions",
        "DrumAccentPads",
        "createDrumAccentOptions",
        "applyDrumAccentToPattern",
        "applyDrumAccent",
        "drum-accent-${accent.id}",
        "drum-accent-pads",
        "DrumFoundationId",
        "DrumFoundationOption",
        "drumFoundationDefinitions",
        "drumFoundationOptions",
        "DrumFoundationPads",
        "createDrumFoundationOptions",
        "applyDrumFoundationToPattern",
        "applyDrumFoundation",
        "drum-foundation-${foundation.id}",
        "drum-foundation-pads",
        "DrumKitPadId",
        "DrumKitPadOption",
        "drumKitPadDefinitions",
        "drumKitPadOptions",
        "DrumKitPads",
        "createDrumKitPadOptions",
        "applyDrumKitPadToProject",
        "applyDrumKitPad",
        "drum-kit-${pad.id}",
        "drum-kit-pads",
        "ArrangementArcPadId",
        "ArrangementArcPadOption",
        "arrangementArcPadDefinitions",
        "arrangementArcPadOptions",
        "ArrangementArcPads",
        "createArrangementArcPadOptions",
        "applyArrangementArcPadToProject",
        "applyArrangementArcPad",
        "arrangement-arc-${pad.id}",
        "arrangement-arc-pads",
        "FinishChecklistCardId",
        "FinishChecklistSummary",
        "finishChecklistSummary",
        "FinishChecklist",
        "createFinishChecklistSummary",
        "finish-checklist",
        "finish-checklist-${card.id}",
        "ReviewQueueItem",
        "ReviewQueueSummary",
        "reviewQueueSummary",
        "ReviewQueue",
        "createReviewQueueSummary",
        "review-queue",
        "review-queue-${item.id}",
        "SnapshotCompareMetricId",
        "SnapshotCompareSummary",
        "snapshotCompareSummary",
        "SnapshotCompare",
        "createSnapshotCompareSummary",
        "createSnapshotCompareProjectProfile",
        "snapshot-compare",
        "snapshot-compare-grid",
        "snapshot-compare-${card.id}",
        "StemAuditionPadId",
        "StemAuditionPadOption",
        "stemAuditionPadDefinitions",
        "stemAuditionPadOptions",
        "StemAuditionPads",
        "createStemAuditionPadOptions",
        "applyStemAuditionPadToMixer",
        "applyStemAuditionPad",
        "stem-audition-${pad.id}",
        "stem-audition-pads",
        "PatternStackId",
        "PatternStackOption",
        "patternStackDefinitions",
        "patternStackOptions",
        "PatternStackPads",
        "createPatternStackOptions",
        "createPatternStackEvents",
        "applyPatternStack",
        "pattern-stack-${stack.id}",
        "pattern-stack-pads",
        "BasslinePadId",
        "BasslinePadOption",
        "basslinePadDefinitions",
        "basslinePadOptions",
        "BasslinePads",
        "createBasslinePadOptions",
        "createBasslinePadNotes",
        "applyBasslinePad",
        "bassline-pad-${pad.id}",
        "bassline-pads",
        "BassGlidePadId",
        "BassGlidePadOption",
        "bassGlidePadDefinitions",
        "bassGlidePadOptions",
        "BassGlidePads",
        "createBassGlidePadOptions",
        "applyBassGlidePadToNotes",
        "applyBassGlidePad",
        "bass-glide-${pad.id}",
        "bass-glide-pads",
        "BassContourId",
        "BassContourOption",
        "bassContourDefinitions",
        "bassContourOptions",
        "BassContourPads",
        "createBassContourOptions",
        "applyBassContourToNotes",
        "applyBassContour",
        "bass-contour-${contour.id}",
        "bass-contour-pads",
        "MelodyMotifId",
        "MelodyMotifOption",
        "melodyMotifDefinitions",
        "melodyMotifOptions",
        "MelodyMotifPads",
        "createMelodyMotifOptions",
        "createMelodyMotifNotes",
        "applyMelodyMotif",
        "melody-motif-${motif.id}",
        "melody-motif-pads",
        "MelodyAccentId",
        "MelodyAccentOption",
        "melodyAccentDefinitions",
        "melodyAccentOptions",
        "MelodyAccentPads",
        "createMelodyAccentOptions",
        "applyMelodyAccentToNotes",
        "applyMelodyAccent",
        "melody-accent-${accent.id}",
        "melody-accent-pads",
        "MelodyContourId",
        "MelodyContourOption",
        "melodyContourDefinitions",
        "MelodyContourPads",
        "createMelodyContourOptions",
        "applyMelodyContourToNotes",
        "applyMelodyContour",
        "melody-contour-${contour.id}",
        "melody-contour-pads",
        "KeyboardCapturePanel",
        "keyboardCaptureKeys",
        "keyboardCaptureEnabled",
        "keyboardCaptureTarget",
        "captureKeyboardNote",
        "isKeyboardCaptureKey",
        "nextKeyboardCaptureStep",
        "addKeyboardCaptureNote",
        "keyboard-capture-toggle",
        "keyboard-capture-target-bass",
        "keyboard-capture-target-melody",
        "keyboard-capture-key-${item.key}",
        "toggleBassNote",
        "toggleMelodyNote",
        "selectedSameNote",
        "NoteInspector",
        "note-probability",
        "note-probability-input",
        "note-chance-badge-${track}-${step}-${pitch}",
        "updateSelectedNoteProbability",
        "moveSelectedNoteStep",
        "moveSelectedNotePitch",
        "moveSelectedNoteOctave",
        "moveSelectedNoteTo",
        "duplicateSelectedNote",
        "note-nudge-left",
        "note-nudge-right",
        "note-pitch-down",
        "note-pitch-up",
        "note-octave-down",
        "note-octave-up",
        "note-duplicate",
        "adjacentTrackPitch",
        "octaveShiftPitch",
        "nextEmptyStepForPitch",
        "SoundFocusPadId",
        "SoundFocusPadOption",
        "soundFocusPadDefinitions",
        "soundFocusPadOptions",
        "SoundDesigner",
        "SoundFocusPads",
        "SoundControl",
        "commitPercentInput",
        "skipNextBlurCommit",
        "applySoundPreset",
        "applySoundFocusPad",
        "applySoundFocusPadToSound",
        "createSoundFocusPadOptions",
        "sameSoundDesign",
        "updateSoundDesign",
        "sound-focus-${pad.id}",
        "sound-focus-pads",
        "sound-preset-readout",
        "sound-preset-${preset}",
        "sound-${id}-input",
        "bass-drive",
        "sidechain-duck",
        "sound-duck-readout",
        "chord-width",
        "ChordEditor",
        "ChordPadId",
        "ChordPadOption",
        "chordPadDefinitions",
        "chordPadOptions",
        "createChordPadOptions",
        "applyChordPad",
        "chord-pad-${pad.id}",
        "chord-pad-row",
        "ChordRhythmId",
        "ChordRhythmOption",
        "chordRhythmDefinitions",
        "chordRhythmOptions",
        "createChordRhythmOptions",
        "applyChordRhythmToEvents",
        "applyChordRhythm",
        "chord-rhythm-${rhythm.id}",
        "chord-rhythm-pads",
        "ChordVoicingId",
        "ChordVoicingOption",
        "chordVoicingDefinitions",
        "createChordVoicingOptions",
        "chordVoicingUpdate",
        "applyChordVoicingPad",
        "chord-voicing-${voicing.id}",
        "chord-voicing-pads",
        "chordInversions",
        "chordInversionLabel",
        "ChordProgressionPreset",
        "selectedChordIndex",
        "selectChordEvent",
        "chordProgressionPresetIds",
        "chordProgressionPresetLabel",
        "createChordProgressionPreset",
        "createNextChordEvent",
        "applyChordProgressionPreset",
        "addChordEvent",
        "deleteChordEvent",
        "deleteSelectedChordEvent",
        "updateChordEvent",
        "moveSelectedChordStep",
        "duplicateSelectedChord",
        "moveSelectedChordInversion",
        "chordEventWithUpdate",
        "sameChordEvent",
        "findChordEventIndex",
        "nextEmptyChordStep",
        "chord-preset-${preset}",
        "chord-add",
        "chord-delete",
        "chord-move-left",
        "chord-move-right",
        "chord-duplicate",
        "chord-invert-down",
        "chord-invert-up",
        "chord-step",
        "chord-root",
        "chord-quality",
        "chord-inversion",
        "chord-inversion-badge",
        "chord-length-input",
        "chord-velocity-input",
        "chord-probability-input",
        "chord-chance-badge-${index}",
        "chanceBadgeLabel",
        "compactChanceBadgeLabel",
        "handleSaveProject",
        "handleOpenProject",
        "handleExportMidi",
        "Exported MIDI",
        "handleExportHandoffSheet",
        "createHandoffSheet",
        "handoffSheetFileName",
        "downloadTextFile",
        "Exported ${fileName}",
        "handleExportStems",
        "export-midi",
        "export-handoff-sheet",
        "export-stems",
        "Invalid project file",
        "patternEventCount",
        "BeatReadiness",
        "BeatReadinessCheck",
        "createBeatReadinessChecks",
        "DeliveryTargets",
        "DeliveryTargetId",
        "CustomDeliveryTarget",
        "activeDeliveryTarget",
        "selectDeliveryTarget",
        "alignDeliveryTarget",
        "updateCustomDeliveryTarget",
        "sameCustomDeliveryTarget",
        "boundedCustomDeliveryText",
        "mixPostureOptions",
        "delivery-targets",
        "delivery-target-current",
        "delivery-target-custom",
        "delivery-target-set-${target.id}",
        "delivery-target-align-${target.id}",
        "delivery-target-set-custom",
        "delivery-target-align-custom",
        "custom-target-name",
        "custom-target-focus",
        "custom-target-bars",
        "custom-target-stems",
        "custom-target-template",
        "custom-target-master",
        "custom-target-posture",
        "deliveryTargetNextMoveAction",
        '"deliveryTarget"',
        "SessionBrief",
        "SessionBriefPanel",
        "updateSessionBrief",
        "clearSessionBrief",
        "sessionBriefStatus",
        "sessionBriefFilledFields",
        "boundedSessionBriefText",
        "session-brief",
        "session-brief-artist",
        "session-brief-vibe",
        "session-brief-reference",
        "session-brief-notes",
        "session-brief-clear",
        "BeatMap",
        "BeatMapSummary",
        "BeatMapStage",
        "BeatMapMetric",
        "createBeatMapSummary",
        "createBeatMapStages",
        "createBeatMapMetrics",
        "createBeatMapActions",
        "chainExpandNextMoveAction",
        "usedPatternSlots",
        "audibleStemTracks",
        "weakestTone",
        "GrooveCompassCardId",
        "GrooveCompassSummary",
        "createGrooveCompassSummary",
        "grooveCompassFocusCard",
        "GrooveCompass",
        "groove-compass",
        "groove-compass-headline",
        "groove-compass-detail",
        "groove-compass-grid",
        "groove-compass-${card.id}",
        "Pattern ${project.selectedPattern} groove compass",
        "Select a drum step for pocket detail",
        "Timing Feel",
        "Hat Motion",
        "ComposerGuideCardId",
        "ComposerGuideSummary",
        "createComposerGuideSummary",
        "composerGuideFocus",
        "ComposerGuide",
        "composer-guide",
        "composer-guide-headline",
        "composer-guide-detail",
        "composer-guide-grid",
        "composer-guide-${card.id}",
        "Beat has a complete writing path",
        "is the next writing focus",
        "Needs low end",
        "Handoff ready",
        "ComposerActionCommand",
        "ComposerActionArea",
        "ComposerAction",
        "ComposerActionsSummary",
        "ComposerStyleActionGoals",
        "ComposerStyleActionProfile",
        "composerStyleActionProfiles",
        "createComposerActionsSummary",
        "composerActionStyleProfile",
        "composerActionPriority",
        "composerActionSort",
        "composerActionTone",
        "composerActionsFocus",
        "composerDrumFoundation",
        "runComposerAction",
        "ComposerActions",
        "composer-actions",
        "composer-actions-headline",
        "composer-actions-detail",
        "composer-actions-grid",
        "composer-action-${action.id}",
        "composer-action-preview-${action.id}",
        "ComposerActionResultMetric",
        "ComposerActionResult",
        "composerActionResult",
        "setComposerActionResult",
        "createComposerActionResult",
        "composerActionResultMetricSnapshots",
        "composerActionFollowupCues",
        "ComposerActionResultStrip",
        "composer-action-result",
        "composer-action-result-title",
        "composer-action-result-detail",
        "composer-action-result-status",
        "composer-action-result-scope",
        "composer-action-result-impact",
        "composer-action-result-safety",
        "composer-action-result-followup",
        "composer-action-result-audition",
        "composer-action-result-next-check",
        "composer-action-result-metrics",
        "composer-action-result-metric-${metric.id}",
        "auditionCue: string",
        "nextCheck: string",
        "scope: string",
        "impact: string",
        "safety: string",
        "Undoable pattern edit",
        "Undoable lane edit",
        "Undoable form edit",
        "Undoable master edit",
        '"drumFoundation"',
        '"bassline"',
        '"chordProgression"',
        '"melodyMotif"',
        "Drum Foundation",
        "808 Bassline",
        "Chord Progression",
        "Melody Motif",
        "BeatPassport",
        "BeatPassportSummary",
        "BeatPassportMetric",
        "createBeatPassportSummary",
        "beat-passport",
        "beat-passport-grid",
        "beat-passport-${metric.id}",
        "HandoffPack",
        "HandoffPackItem",
        "createHandoffPackItems",
        "handoff-pack",
        "handoff-pack-grid",
        "handoff-pack-${item.id}",
        "handoff-pack-action-${item.id}",
        "onExportWav",
        "onExportStems",
        "onExportMidi",
        "onExportHandoffSheet",
        "StructureLens",
        "StructureLensSignal",
        "StructureLensSummary",
        "createStructureLensSummary",
        "createStructureLensActions",
        "structureHookSignal",
        "structureArcSignal",
        "structure-lens",
        "structure-lens-signals",
        "structure-lens-${signal.id}",
        "structure-lens-action-${action.id}",
        "SongFormMetricId",
        "SongFormSegment",
        "SongFormOverviewSummary",
        "songFormOverviewSummary",
        "SongFormOverview",
        "createSongFormOverviewSummary",
        "createSongFormSegments",
        "compactSectionFlow",
        "patternEventTotal",
        "song-form-overview",
        "song-form-timeline",
        "song-form-metric-${metric.id}",
        "song-form-segment-${segment.index}",
        "NextMove",
        "NextMoveAction",
        "NextMoveCommand",
        "NextMoveResult",
        "NextMoveResultStrip",
        "createNextMoveResult",
        "nextMoveResultMetricSnapshot",
        "nextMoveResultFollowup",
        "nextMoveResult",
        "createNextMoveActions",
        "primaryNextMoveAction",
        "patternChainNextMoveAction",
        "fullArrangementNextMoveAction",
        "runNextMove",
        '"patternChain"',
        '"chainExpand"',
        "Sketch an 8-bar Pattern Chain",
        "Beat Map",
        "beat-map",
        "beat-map-headline",
        "beat-map-stages",
        "beat-map-metrics",
        "beat-map-action-${action.id}",
        "next-move",
        "next-move-title",
        "next-move-action-${primaryAction.id}",
        "next-move-result",
        "next-move-result-title",
        "next-move-result-metric",
        "next-move-result-audition",
        "next-move-result-next-check",
        "Review Mix Coach",
        "QuickAction",
        "QuickActionResult",
        "QuickActionResultStrip",
        "createQuickActionResult",
        "quickActionResultMetricSnapshot",
        "quickActionResultFollowup",
        "quickActionResult",
        "QuickActions",
        "quickActionsOpen",
        "quickActionQuery",
        "wantsQuickActions",
        "openQuickActions",
        "closeQuickActions",
        "runQuickAction",
        "createQuickActions",
        "filterQuickActions",
        "quickActionSearchTokens",
        "quick-actions-open",
        "quick-actions",
        "quick-actions-search",
        "quick-action-${action.id}",
        "quick-action-result",
        "quick-action-result-title",
        "quick-action-result-metric",
        "quick-action-result-audition",
        "quick-action-result-next-check",
        "arrangedPatternData",
        "drumHitCount",
        "drumReadinessCheck",
        "bassReadinessCheck",
        "harmonyReadinessCheck",
        "arrangementReadinessCheck",
        "exportReadinessCheck",
        "beatReadinessChecks",
        "project-snapshots",
        "snapshot-count",
        "snapshot-save",
        "snapshot-empty",
        "snapshot-item-${snapshot.id}",
        "snapshot-restore-${snapshot.id}",
        "snapshot-delete-${snapshot.id}",
        "beat-readiness",
        "beat-readiness-summary",
        "beat-readiness-check-${check.id}",
        "PatternCompareSummary",
        "PatternCompareStrip",
        "patternCompareSummaries",
        "createPatternCompareSummaries",
        "cuePattern",
        "usePatternInSelectedBlock",
        "selectPattern",
        "copySelectedPattern",
        "clearSelectedPattern",
        "applyPatternVariation",
        "applyPatternFill",
        "patternVariationPresetIds",
        "patternVariationPresetLabel",
        "patternFillPresetIds",
        "patternFillPresetLabel",
        "applyPatternFillPreset",
        "pattern-copy-${pattern}",
        "pattern-compare",
        "pattern-compare-${summary.slot}",
        "pattern-cue-${summary.slot}",
        "pattern-use-${summary.slot}",
        "pattern-variation-${preset}",
        "pattern-fill-${preset}",
        "pattern-clear",
        "selectedArrangementIndex",
        "ArrangementTemplateId",
        "arrangementTemplateIds",
        "arrangementTemplateLabel",
        "PatternChainId",
        "patternChainIds",
        "patternChainLabel",
        "createPatternChain",
        "expandPatternChainArrangement",
        "applyPatternChain",
        "expandPatternChain",
        "cyclePatternChainStep",
        "patternChainReadout",
        "nextPatternSlot",
        "pattern-chain-current",
        "pattern-chain-${chain}",
        "pattern-chain-expand",
        "pattern-chain-step-editor",
        "pattern-chain-step-${index}",
        "pattern-chain-step-pattern-${index}",
        "ArrangementMovePreset",
        "ArrangementFocusPresetId",
        "ArrangementFocusPanel",
        "ArrangementFocusSummary",
        "arrangementFocusPresets",
        "selectedArrangementFocus",
        "createArrangementFocusSummary",
        "suggestedArrangementFocusPreset",
        "applyArrangementFocusPreset",
        "arrangementMovePresetIds",
        "arrangementMovePresetLabel",
        "applyArrangementMovePreset",
        "applyArrangementMoveToSelected",
        "arrangementMuteTrackIds",
        "arrangementMuteTrackLabel",
        "arrangementTotalBars",
        "createArrangementTemplate",
        "minArrangementBars",
        "maxArrangementBars",
        "arrangementEnergyGain",
        "normalizeArrangementEnergy",
        "normalizeArrangementMutedTracks",
        "normalizeArrangementBars",
        "applyArrangementTemplate",
        "updateArrangementBlock",
        "toggleArrangementTrackMute",
        "duplicateArrangementBlock",
        "splitArrangementBlock",
        "mergeArrangementBlock",
        "canMergeArrangementBlock",
        "selectedArrangementNextBlock",
        "splitAfterBars",
        "clampSplitAfterBars",
        "moveArrangementBlock",
        "deleteArrangementBlock",
        "Merged arrangement blocks",
        "Selected arrangement block editor",
        "arrangement-template-${template}",
        "arrangement-section-select",
        "arrangement-bars-input",
        "arrangement-split-after",
        "arrangement-split",
        "arrangement-merge",
        "arrangement-energy-input",
        "arrangement-move-${preset}",
        "arrangement-focus",
        "arrangement-focus-summary",
        "arrangement-focus-${preset.id}",
        "hook-peak-focus",
        "arrangement-track-mute-${track}",
        "arrangement-duplicate",
        "arrangement-delete",
        "barCountLabel",
        "MixBalancePadId",
        "MixBalancePadOption",
        "mixBalancePadDefinitions",
        "mixBalancePadOptions",
        "MixBalancePads",
        "createMixBalancePadOptions",
        "applyMixBalancePadToMixer",
        "applyMixBalancePad",
        "sameMixerChannels",
        "mix-balance-${pad.id}",
        "mix-balance-pads",
        "updateMixerChannel",
        "normalizeMixerEq",
        "mixer-low-cut",
        "mixer-low-cut-input",
        "mixer-air",
        "mixer-air-input",
        "mixer-drive",
        "mixer-drive-input",
        "mixer-glue",
        "mixer-glue-input",
        "mixer-send",
        "mixer-send-input",
        "Cut {percentLabel(channel.lowCut)}",
        "Air {percentLabel(channel.air)}",
        "Drive {percentLabel(channel.drive)}",
        "Glue {percentLabel(channel.glue)}",
        "Space {percentLabel(channel.send)}",
        "StemLevelMeter",
        "analyzeStemExports",
        "stemAnalyses",
        "isStemTrackId",
        "stem-level-meter-${trackId}",
        "stem-peak-db-${trackId}",
        "stem-rms-db-${trackId}",
        "stem-headroom-db-${trackId}",
        "MixCoach",
        "MixCoachCheck",
        "MixFixPreset",
        "MixFixAction",
        "applyMixFixPreset",
        "createMixFixActions",
        "applyMixFixToProject",
        "mixFixPresetLabel",
        "mix-fix-${fix.preset}",
        '"headroom"',
        '"stem_balance"',
        '"low_end"',
        "createMixCoachChecks",
        "masterHeadroomCheck",
        "limiterCheck",
        "stemBalanceCheck",
        "lowEndBlendCheck",
        "mixCoachSummary",
        "mix-coach",
        "mix-coach-summary",
        "mix-coach-check-${check.id}",
        "applyMasterPreset",
        "applyMasterFinishPad",
        "applyMasterFinishPadToProject",
        "createMasterFinishPadOptions",
        "masterFinishChangedCount",
        "masterChannelVolumeDb",
        "clampMasterCeilingDb",
        "mixer-pan",
        "mixer-pan-input",
        "mixer-solo",
    ],
    "src/audio/scheduler.ts": [
        "scheduleAheadSeconds",
        "startRealtimePlayback",
        "getProject",
        "currentProject",
        "masterGain.gain.setTargetAtTime",
        "scheduleMetronomeClick",
        "metronomeEnabled",
        "PlaybackMode",
        "playbackContextForStep",
        "startBar",
        "options.startBar",
        "arrangementContextForBar",
        "arrangementEnergyGain",
        "energyGain",
        "mutedTracks",
        "arrangementTrackMix",
        "onStep",
        "activePattern",
        "chordPitches",
        "SoundDesign",
        "drumStepTimingMs",
        "drumStepVelocity",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "hatRepeatCount",
        "sidechainGainForStep",
        "lowCut",
        "air",
        "drive",
        "glue",
        "channelHighpassHz",
        "channelAirFilterHz",
        "connectChannelGlue",
        "driveCurve",
        "channelMix",
        "createSpaceBus",
        "connectScheduledOutput",
        "createStereoPanner",
    ],
    "src/audio/render.ts": [
        "patternForSlot",
        "arrangementBlock",
        "arrangementBarCount",
        "arrangementBlockForBar",
        "arrangementTotalBars",
        "arrangementEnergyGain",
        "energyGain",
        "arrangementBlockMutesTrack",
        "mutedChannelMix",
        "arrangementChannelMix",
        "createRenderNoiseSeed",
        "seededNoiseSample",
        "hashString",
        "hashNumbers",
        "normalizeArrangementBars",
        "chordPitches",
        "SoundDesign",
        "drumStepTimingMs",
        "drumStepVelocity",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "hatRepeatCount",
        "sidechainGainForStep",
        "lowCut",
        "air",
        "drive",
        "glue",
        "send",
        "spaceSendMix",
        "addToneWithSend",
        "addNoiseWithSend",
        "applySpaceReturn",
        "channelHighpassHz",
        "channelDriveSample",
        "channelGlueSample",
        "toneEqFactor",
        "addTone",
        "channelMix",
        "masterOutputGain",
        "stemTrackIds",
        "StemTrackId",
        "StemExportAnalyses",
        "ExportAnalysis",
        "analyzeExport",
        "analyzeStemExports",
        "exportStems",
        "stemTrackLabel",
    ],
    "src/audio/midi.ts": [
        "createMidiFile",
        "exportMidi",
        "midiFileName",
        "MThd",
        "MTrk",
        "ticksPerQuarter",
        "ticksPerStep",
        "arrangementBlockForBar",
        "arrangementBlockMutesTrack",
        "arrangementEnergyGain",
        "drumStepShouldPlay",
        "hatRepeatCount",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "chordPitches",
        "GrooveForge Drums",
        "GrooveForge 808",
        "GrooveForge Synth",
        "GrooveForge Chords",
        "audio/midi",
    ],
    "src/domain/workstation.ts": [
        "styleProfiles",
        '"jersey"',
        '"phonk"',
        "Jersey Club",
        "Phonk",
        "starterProject",
        "StyleProfile",
        "DeliveryTarget",
        "DeliveryTargetId",
        "FixedDeliveryTargetId",
        "CustomDeliveryTarget",
        "MixPosture",
        "SessionBrief",
        "sessionBrief",
        "defaultSessionBrief",
        "maxSessionBriefFieldLength",
        "maxSessionBriefNotesLength",
        "maxCustomDeliveryTargetNameLength",
        "maxCustomDeliveryTargetFocusLength",
        "minDeliveryTargetBars",
        "maxDeliveryTargetBars",
        "minDeliveryTargetStemGoal",
        "maxDeliveryTargetStemGoal",
        "normalizeSessionBrief",
        "normalizeBriefText",
        "isSessionBriefInput",
        "customDeliveryTarget",
        "fixedDeliveryTargetIds",
        "deliveryTargetIds",
        "deliveryTargets",
        "deliveryTargetLabels",
        "defaultDeliveryTarget",
        "defaultCustomDeliveryTarget",
        "deliveryTargetLabel",
        "deliveryTargetFocus",
        "deliveryTargetForId",
        "activeDeliveryTarget",
        "applyDeliveryTarget",
        "applyDeliveryTargetMixer",
        "normalizeDeliveryTargetId",
        "normalizeCustomDeliveryTarget",
        "normalizeDeliveryTargetBars",
        "normalizeDeliveryTargetStemGoal",
        "CustomDeliveryTargetInput",
        "isCustomDeliveryTargetInput",
        "isMixPosture",
        "metronomeEnabled",
        "bassPitchLanes",
        "melodyPitchLanes",
        "scalePitches",
        "retargetPitchNameToKey",
        "retargetPitchToKey",
        "retargetPatternKey",
        "retargetProjectKey",
        "serializeProjectFile",
        "parseProjectFile",
        "PatternData",
        "ProjectCoreState",
        "ProjectSnapshot",
        "maxProjectSnapshots",
        "maxProjectSnapshotNameLength",
        "nextProjectSnapshotName",
        "normalizeProjectSnapshotName",
        "createProjectSnapshot",
        "saveProjectSnapshot",
        "restoreProjectSnapshot",
        "deleteProjectSnapshot",
        "renameProjectSnapshot",
        "projectSnapshotSummary",
        "normalizeProjectSnapshots",
        "cloneProjectCore",
        "DrumVelocities",
        "DrumTimings",
        "DrumProbabilities",
        "probability: number",
        "DrumGroovePreset",
        "drumGroovePresetIds",
        "drumGroovePresetLabel",
        "applyDrumGroovePreset",
        "PatternVariationPreset",
        "patternVariationPresetIds",
        "patternVariationPresetLabel",
        "createPatternVariation",
        "PatternFillPreset",
        "patternFillPresetIds",
        "patternFillPresetLabel",
        "applyPatternFillPreset",
        "clearPatternTail",
        "drumStepTimingMs",
        "drumStepVelocity",
        "normalizeDrumTimingMs",
        "grooveVelocity",
        "grooveTimingMs",
        "hatRepeatCount",
        "drumStepProbability",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "normalizeDrumProbability",
        "normalizeEventProbability",
        "normalizeDrumVelocity",
        "normalizeHatRepeat",
        "sidechainGainForStep",
        "ChordEvent",
        "chordQualities",
        "ChordInversion",
        "chordInversions",
        "chordInversionLabel",
        "normalizeChordInversion",
        "chordPitches",
        "SoundDesign",
        "soundPresetIds",
        "soundPresetDesign",
        "soundPresetLabel",
        "patternSlots",
        "createStylePatternSet",
        "styleSoundPreset",
        "stylePatternBlueprints",
        "BeatBlueprint",
        "BeatBlueprintId",
        "beatBlueprintIds",
        "beatBlueprints",
        "applyBeatBlueprint",
        "applyBeatBlueprintMixer",
        "createEmptyPatternData",
        "ArrangementSection",
        "ArrangementMuteTrack",
        "ArrangementMovePreset",
        "arrangementMovePresetIds",
        "arrangementMovePresetLabel",
        "arrangementMovePresetLabels",
        "applyArrangementMovePreset",
        "arrangementMuteTrackIds",
        "arrangementMuteTrackLabel",
        "arrangementBlockMutesTrack",
        "normalizeArrangementMutedTracks",
        "arrangementSections",
        "minArrangementBars",
        "maxArrangementBars",
        "normalizeArrangementEnergy",
        "arrangementEnergyGain",
        "normalizeArrangementBars",
        "arrangementTotalBars",
        "masterPresets",
        "masterPresetCeilingDb",
        "normalizeProjectState",
        "MixerChannelInput",
        "normalizeMixerEq",
        "normalizeMixerChannels",
        "lowCut",
        "air",
        "drive",
        "glue",
        "send",
    ],
}


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def check_required_paths(errors: list[str]) -> None:
    for path in REQUIRED_PATHS:
        if not (ROOT / path).exists():
            errors.append(f"missing required path: {path}")


def check_root_markdown(errors: list[str]) -> None:
    allowed = {"README.md", "AGENTS.md"}
    found = {path.name for path in ROOT.glob("*.md")}
    extra = sorted(found - allowed)
    if extra:
        errors.append(f"unexpected root markdown files: {', '.join(extra)}")


def check_forbidden_paths(errors: list[str]) -> None:
    if (ROOT / "docs/plan").exists():
        errors.append("forbidden path exists: docs/plan")


def check_plan_names(errors: list[str]) -> None:
    for directory in [
        ROOT / "docs/exec_plans/active",
        ROOT / "docs/exec_plans/completed",
    ]:
        if not directory.exists():
            continue
        for path in directory.glob("*.md"):
            if not PLAN_RE.fullmatch(path.name):
                errors.append(f"invalid plan filename: {rel(path)}")


def check_text_expectations(errors: list[str]) -> None:
    for file_path, needles in TEXT_EXPECTATIONS.items():
        text = (ROOT / file_path).read_text(encoding="utf-8")
        for needle in needles:
            if needle not in text:
                errors.append(f"{file_path} missing text: {needle}")


def check_official_sources(errors: list[str]) -> None:
    text = (ROOT / "docs/references/official-sources.md").read_text(encoding="utf-8")
    if "| TODO |" in text:
        errors.append("official sources still contain placeholder table rows")


def check_strict_todos(errors: list[str]) -> None:
    ignored_prefixes = {
        ".worktree/",
        "dist/",
        "dist-electron/",
        "harness/templates/",
        "node_modules/",
    }
    for path in ROOT.rglob("*.md"):
        relative = rel(path)
        if any(relative.startswith(prefix) for prefix in ignored_prefixes):
            continue
        text = path.read_text(encoding="utf-8")
        if "TODO" in text:
            errors.append(f"strict mode found TODO in {relative}")


def check_offline_render_determinism(errors: list[str]) -> None:
    render_text = (ROOT / "src/audio/render.ts").read_text(encoding="utf-8")
    if "Math.random" in render_text:
        errors.append("src/audio/render.ts must not use Math.random in the offline render path")


def run_checks(strict: bool = False) -> list[str]:
    errors: list[str] = []
    check_required_paths(errors)
    check_root_markdown(errors)
    check_forbidden_paths(errors)
    check_plan_names(errors)
    check_text_expectations(errors)
    check_official_sources(errors)
    check_offline_render_determinism(errors)
    if strict:
        check_strict_todos(errors)
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate the GrooveForge project base.")
    parser.add_argument("--strict", action="store_true", help="Fail on TODO markers outside templates.")
    args = parser.parse_args(argv)

    errors = run_checks(strict=args.strict)
    if errors:
        print("QA failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    mode = "strict " if args.strict else ""
    print(f"GrooveForge {mode}QA passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
