#!/usr/bin/env python3
"""Validate the GrooveForge project base."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PLAN_RE = re.compile(r"plan-\d{3}-[a-z0-9][a-z0-9-]*\.md$")

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "package.json",
    "index.html",
    "vite.config.ts",
    "tsconfig.json",
    "tsconfig.electron.json",
    "electron/main.ts",
    "electron/preload.ts",
    "src/main.tsx",
    "src/ui/App.tsx",
    "src/audio/midi.ts",
    "src/domain/workstation.ts",
    "src/audio/render.ts",
    "src/audio/scheduler.ts",
    "src/styles.css",
    "docs/architecture/harness.md",
    "docs/architecture/product-architecture.md",
    "docs/product/product.md",
    "docs/quality/rules.md",
    "docs/privacy/principles.md",
    "docs/references/official-sources.md",
    "docs/exec_plans/active",
    "docs/exec_plans/completed",
    "docs/meetings/index.md",
    "docs/reviews",
    "harness/templates/exec-plan.md",
    "harness/templates/meeting.md",
    "harness/templates/review.md",
]

TEXT_EXPECTATIONS = {
    "README.md": [
        "making beats across genres",
        "beat workstation first, not a sampler-first app",
        "Concept lock: GrooveForge is not a sampling app.",
        "all-genre beat-production mini DAW",
        "Direct composition is the product spine",
        "program drums, 808/bass, melody, chords, FX, and automation as editable musical events",
        "opening a compact beat-making DAW, not a sample browser",
        "BPM/key/style -> pattern programming -> drums -> 808/bass -> melody/chords -> sound design -> arrangement -> mixing -> mastering -> export",
        "sample import -> chop/slice -> pitch/stretch -> one-shot or sampler mapping",
        "Sampling is a secondary add-on.",
        "A complete GrooveForge beat must be possible with no imported audio.",
        "If a draft, screen, or roadmap has to choose what appears first, the answer is direct beat creation",
        "Keep first-run UI and default navigation focused on making beats across genres",
        "Treat sample-free beat creation as the proof of the product",
        "local project save/load",
        "Key changes that retarget Pattern A/B/C 808, synth, and chord-root event data",
        "Style selector that applies editable genre groove templates for Trap, Drill, Boom Bap, Lo-fi, House, R&B, Jersey Club, Phonk, Garage, and Experimental",
        "Style Inspector with Style Quick Picks that explain and apply each genre's BPM range, active/default swing, bass role, melody role, sound preset, and Pattern A/B/C event density from local project data.",
        "Beat Blueprints for sample-free project starts that apply style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset while staying fully editable.",
        "drum velocity, event chance, chance badges, microtiming, one-click groove humanization, hat repeat dynamics, Desktop Keyboard Capture for scale-locked 808/Synth note entry, Melody Motif Pads, and selected-note move/transpose/duplicate tools",
        "Desktop Keyboard Capture for scale-locked 808/Synth note entry",
        "Key-aware chord progression presets with Chord Pads, chord add/delete, selected-chord move/duplicate/inversion tools, and per-chord chance controls",
        "kick-to-808 sidechain ducking",
        "Delivery Targets for starter sketch, vocal session, beat-store demo, club demo, and one editable custom outcome, with explicit target alignment for arrangement length, master preset, and mix posture.",
        "Independent Pattern A/B/C variations with Pattern Compare cue/use cards, deterministic Subtle/Hook/Break tools, one-click Drum Fill/808 Pickup/Melody Turn tail moves, copy/clear tools, and editable arrangement blocks with Arrangement Focus presets, one-click Drop/Build/Hook Lift moves, per-track mutes, audible energy, bar length, split, merge, duplicate, move, and delete controls",
        "Pattern Chain presets, an 8-step chain editor, and Chain Expand that turn Pattern A/B/C variations into editable arrangement sketches and longer song-form outlines.",
        "Read-only Beat Readiness checks for drums, 808, melody/chords, arrangement, and export completeness.",
        "Beat Map production overview that uses the selected fixed or custom Delivery Target to show beginner workflow stages, producer-facing song/pattern/mix/stem metrics, and explicit local action buttons from the current project state.",
        "Next Move strip that turns readiness/export state into explicit local actions such as Blueprint, target alignment, Pattern Compare, Pattern Fill, Pattern Chain, Hook Lift, Save Slot, and Mix Check.",
        "Arrangement templates for 8-bar loop, full beat, hook-first, and breakdown song structures with explicit section lengths.",
        "Desktop editing shortcuts, Keyboard Capture, and Quick Actions command search for arrangement playback, Pattern A/B/C switching, selected event deletion, save, open, undo, redo, snapshots, blueprints, pattern fills, Arrangement Focus, mix fixes, and export.",
        "Undo/redo edit history",
        "Project Snapshots for local idea slots that can save, rename, restore, and delete beat states inside the project file.",
        "Realtime transport loop controls for Song, selected Block, and Pattern audition",
        "metronome toggle with accented downbeat clicks",
        "Live playback that follows future pattern, arrangement track mutes, BPM, mixer, sound, and master edits without forcing users to stop and restart.",
        "Arrangement Focus presets, one-click Drop/Build/Hook Lift moves, per-track mutes, per-block bar lengths, split/merge controls, and audible energy",
        "Basic mixer volume/pan/mute/solo, channel low-cut/air EQ, Drive/Glue mix controls, Space send FX",
        "deterministic Mix Coach checks with explicit Mix Fix actions",
        "per-stem export level meters",
        "deterministic Mix Coach checks with explicit Headroom/Stem Balance/Low End Mix Fix actions",
        "arrangement MIDI export for DAW handoff",
        "reproducible export peak/RMS/headroom meter",
        "transport with arrangement playback, Pattern preview, Song/Block/Pattern loop audition, and a realtime-only metronome",
        "Keyboard Capture for 808/Synth note entry",
        "Quick Actions command search",
        "Project Snapshots",
        "Beat Blueprints for sample-free editable project starts",
        "Delivery Targets for starter sketch, vocal session, beat-store demo, club demo, and custom outcomes",
        "local Next Move actions that can align the selected target or suggest Pattern Chain",
        "Pattern Compare cue/use cards",
        "deterministic Pattern variation tools",
        "Pattern Fill tail moves",
        "editable scale-aware 808/melody lanes with Melody Motif Pads, note chance badges, and selected-note move/transpose/duplicate tools",
        "channel low-cut/air EQ",
        "Drive/Glue mix controls",
        "chord progression presets plus Chord Pads, add/delete/selected-chord move/duplicate/inversion/chance controls",
        "Sound presets and Studio tone controls",
        "read-only Beat Readiness checks",
        "Session Brief for bounded local artist, vibe, reference, and handoff notes stored in the project file.",
        "Session Brief for local artist/vibe/reference/handoff notes",
        "target-aware Beat Map workflow and producer metrics",
        "local Next Move actions that can align the selected target or suggest Pattern Chain when arrangement structure is weak",
        "Pattern Chain 8-bar sketches with per-step A/B/C cycling plus Chain Expand song-form outlining",
        "Space send FX",
        "per-stem export level meters",
        "deterministic Mix Coach checks",
        "reproducible export peak/RMS/headroom meter",
        "one-click stem export",
        "arrangement MIDI export",
        "Local Handoff Sheet text export that summarizes title, BPM/key/style, Delivery Target, Session Brief, arrangement, export meter, and stem meter data for collaboration and review.",
        "Handoff Sheet text export",
        "npm run desktop",
    ],
    "AGENTS.md": [
        "No Exec Plan, No Work",
        "GrooveForge is an all-genre, event-based beat workstation",
        "First-run UI, default navigation, and roadmap order should lead with direct beat composition",
    ],
    "docs/product/product.md": [
        "It is beat-first, not sampler-first.",
        "Corrected concept: GrooveForge is a beat-production mini DAW",
        "It can support sampling later, but sampling is not the project identity, first-run workflow, MVP proof, or core architecture.",
        "The center is making a beat directly, not finding a sample to start from.",
        "Pattern programming for all supported styles.",
        "Optional sampling module, later and outside the MVP:",
        "audio sample import -> chop/slice -> pitch/stretch -> one-shot or sampler mapping",
        "No user should need a sample to make the first complete beat.",
        "When sampling appears later, it should behave like an optional sound source or instrument layer inside the beat workstation",
        "샘플 없이도 8마디 비트를 만들고 WAV로 export할 수 있어야 한다.",
        "This sentence supersedes any sampling-first interpretation of the brief.",
        "Sampling can be useful, but it must stay behind the composition engine",
        "Primary navigation and the first empty project should expose beat-making controls before sample workflows",
        "Sampling entry points, when added, should be opt-in secondary paths",
        "it means a pattern, MIDI, or automation container",
        "Local project save/load",
        "Key changes retarget Pattern A/B/C 808/bass, melody, and chord-root musical events",
        "Style selector that applies key-aware editable groove templates for Trap, Drill, Boom Bap, Lo-fi, House, R&B, Jersey Club, Phonk, Garage, and Experimental",
        "Style Inspector with Style Quick Picks that derive read-only BPM range, active/default swing, bass role, melody role, sound preset, and Pattern A/B/C event density from local style/profile/project data while applying styles through the existing undoable style-selection path.",
        "Beat blueprints: sample-free editable project starts that combine style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset.",
        "Delivery Targets: local starter sketch, vocal session, beat-store demo, club demo, and editable custom targets that can be set without changing the beat or explicitly aligned to arrangement length, master preset, and mix posture.",
        "Session Brief: bounded local artist, vibe, reference, and notes fields stored in the project file for beat intent and handoff context.",
        "Beat Blueprints that apply complete sample-free project starts across style, key, BPM, Pattern A/B/C events, arrangement template, sound preset, mixer balance, and master preset while preserving manual editing.",
        "Desktop Keyboard Capture for scale-locked 808/Synth note entry",
        "editable drum velocity, probability, visible chance badges, microtiming, one-click groove humanization, and hat repeat dynamics",
        "note chance badges, selected-note move/transpose/duplicate tools, saturation direction, and kick-to-808 sidechain ducking",
        "kick-to-808 sidechain ducking",
        "sidechain ducking",
        "editable step/root/quality/inversion/length/velocity/chance, visible chance badges, add/delete controls, and selected-chord move/duplicate/inversion tools",
        "Pattern editor: drum step sequencer, bass grid, chord progression with key-aware Chord Pads, melody grid with Melody Motif Pads, Desktop Keyboard Capture for scale-locked 808/Synth note entry, Pattern Compare cue/use cards, variation A/B/C, and one-click Pattern Fill tail moves.",
        "Independent Pattern A/B/C storage with Pattern Compare cue/use cards for density and arrangement-use decisions, deterministic Subtle/Hook/Break variation tools, one-click Drum Fill/808 Pickup/Melody Turn/Clear Tail moves, plus copy/clear tools for drum, bass, chord, and melody variations",
        "Read-only Beat Readiness checks for drums, 808/bass, melody/chords, arrangement structure, and export signal status.",
        "Delivery Targets stored in project state with safe migration for older files; setting a fixed or custom target changes only the target, editable custom fields stay bounded in local project data, and explicit target alignment can update arrangement template, master preset, master ceiling, and mix posture through undoable project history.",
        "Session Brief stored in local project state with bounded artist, vibe, reference, and notes text so beginners can clarify intent and producers can keep handoff context without media uploads or cloud collaboration.",
        "Beat Map production overview derived from local project, selected fixed or custom Delivery Target, Beat Readiness, export analysis, and stem analysis state, showing beginner workflow stages, producer-facing song/pattern/export/stem metrics, and explicit local action buttons without mutating project state unless clicked.",
        "Next Move strip that gives one primary recommended action and secondary local actions from the current readiness/export state, including target alignment, Pattern Compare, and Pattern Chain when arrangement structure is weak, without mutating Beat Readiness.",
        "Beat Map: deterministic production overview that maps the current beat into Start, Compose, Arrange, Polish, and Deliver stages against the selected fixed or custom Delivery Target, plus song length, Pattern A/B/C usage, export, and stem metrics for faster beginner and producer decisions.",
        "Quick Actions: searchable local command palette for transport, project, creative, arrangement, mix, and export actions.",
        "Undo/redo edit history for project-level pattern, arrangement, mixer, sound, and master changes",
        "Project snapshots: local idea slots for saving, renaming, restoring, and deleting beat states inside the project file.",
        "Project Snapshots that save, rename, restore, and delete local beat idea states inside the `.grooveforge.json` file without cloud sync or nested snapshot recursion.",
        "Desktop editing shortcuts, Keyboard Capture, and Quick Actions command search for arrangement playback, Pattern A/B/C selection, selected drum/note deletion, save, open, undo, redo, snapshots, blueprints, pattern fills, Arrangement Focus, mix fixes, and export while leaving focused inputs alone.",
        "Transport playback modes for full arrangement playback by default, selected-block loop audition, and fast selected-pattern preview while editing.",
        "Realtime metronome toggle with accented downbeat clicks",
        "without adding click audio to WAV or stem export",
        "Live playback reads the current project while scheduling future steps",
        "selected-pattern preview, arrangement block edits, arrangement track mutes, arrangement length, arrangement energy, BPM, mixer, sound, and master changes can be heard without stopping and restarting",
        "Chord progression track with scale-locked roots, key-aware Chord Pads, key-aware progression presets",
        "editable step/root/quality/inversion/length/velocity/chance, visible chance badges, add/delete controls, and selected-chord move/duplicate/inversion tools",
        "Simple synth melody track with editable scale-aware grid, Melody Motif Pads, Desktop Keyboard Capture, velocity control, note chance badges, and selected-note move/transpose/duplicate tools.",
        "Sound design presets and Studio tone controls",
        "Editable arrangement blocks and templates",
        "Arrangement Focus presets",
        "Pattern Chain presets, per-step A/B/C cycling, and Chain Expand song-form outlining that edit only arrangement block assignments while preserving Pattern A/B/C musical event data, mixer state, sound design, master state, and existing export paths.",
        "one-click Drop/Build/Hook Lift moves",
        "8-bar loop, full beat, hook-first, and breakdown structures",
        "per-block track mutes",
        "audible per-block energy",
        "per-block bar length",
        "split/merge controls",
        "duplicate, move, and delete controls",
        "Mixer volume, pan, mute, solo, low-cut/air EQ, Drive/Glue mix controls, built-in Space send FX, per-stem export level meters, deterministic Mix Coach checks, and explicit Headroom/Stem Balance/Low End Mix Fix actions reflected in deterministic render feedback",
        "channel low-cut/air EQ",
        "Drive/Glue mix controls",
        "per-stem export level meters",
        "deterministic Mix Coach checks",
        "Reproducible export peak/RMS/headroom meter with limiter activity status",
        "WAV export through deterministic offline rendering",
        "Stem export through deterministic offline rendering",
        "MIDI export as a deterministic Standard MIDI File with drum, 808, synth, and chord tracks from the current arrangement.",
        "Handoff Sheet export as a local plain text summary of title, BPM/key/style, Delivery Target, Session Brief, arrangement blocks, export meter, and stem meter data without media upload or compliance claims.",
        "Feature priority follows the beat-workstation core:",
        "P3 | sampling and plugin hosting",
    ],
    "docs/quality/rules.md": [
        "QA and review are separate loops.",
        "python3 harness/scripts/run_quality_gate.py",
        "Metronome work must keep click playback realtime-only",
        "keep WAV/stem exports free of metronome audio",
        "Drum probability work must migrate old patterns to 100% chance",
        "808, melody, and chord chance work must migrate older musical events to 100% chance",
        "Chance badge work must keep badges read-only",
        "use deterministic probability gates so exported audio is reproducible",
        "Project file work must reject invalid imports",
        "preserve edited drum, bass, chord, melody, sound design",
        "Project Snapshot work must store snapshots as local project-file data",
        "keep snapshot payloads free of nested snapshots",
        "allow save/rename/restore/delete without cloud sync or accounts",
        "keep snapshot names bounded and normalized",
        "Drum dynamics work must migrate old patterns",
        "Drum microtiming work must migrate old patterns",
        "Groove humanize work must be deterministic",
        "Style groove work must apply key-aware editable Pattern A/B/C event data",
        "Style expansion work must add new genres as first-class `StyleId` entries",
        "every new style must remain editable, undoable through the existing style-selection path, sample-free",
        "Style Inspector and Style Quick Picks work must derive read-only BPM range, active/default swing, bass role, melody role, sound preset, and Pattern A/B/C event density",
        "keep style selection accessible/testable",
        "route quick-pick style changes through the existing undoable style-selection path",
        "Beat Blueprint work must apply deterministic sample-free project starts from local style, key, BPM, Pattern A/B/C event data, arrangement templates, sound presets, mixer balance, and master presets",
        "keep the result fully editable and undoable",
        "Key retarget work must update Pattern A/B/C 808/bass note pitches, melody note pitches, and chord roots by scale degree",
        "Chord progression work must preserve Pattern A/B/C independence",
        "Chord Pad work must derive pad roots and qualities from the current key",
        "keep chord roots and progression presets scale-aware by default",
        "keep add/delete operations undoable",
        "preserve at least one chord event in guided editing",
        "Chord inversion work must migrate older chord events to root position",
        "Selected chord edit tool work must keep chord move, duplicate, delete, and inversion actions scoped to the selected Pattern A/B/C slot",
        "avoid overlapping duplicate or moved chord starts at the same step",
        "Sound design work must keep tone parameters in project state",
        "Sidechain work must keep kick-to-808 ducking",
        "Export meter work must label measurements honestly as peak, RMS, headroom, and limiter activity",
        "Render noise work must keep offline WAV export, stem export, and export meter analysis deterministic from render-relevant project data",
        "avoid `Math.random()` in the offline render path",
        "Stem export work must render isolated drum, 808, synth, and chord WAV files",
        "Stem level meter work must derive drum, 808, synth, and chord meter values from the deterministic offline stem render path",
        "show peak/RMS/headroom honestly without LUFS or true-peak claims",
        "Mix Coach work must derive suggestions only from deterministic full-mix and stem export analysis",
        "communicate peak/RMS/headroom/limiter/stem-balance checks without LUFS, true-peak, platform compliance, or mastering-fix claims",
        "Mix Fix work must run only after explicit user button clicks",
        "route all mixer/master changes through undoable project update paths",
        "keep fixes limited to editable mixer/master state",
        "MIDI export work must write deterministic Standard MIDI Files from editable project events",
        "Handoff Sheet export work must write a local plain text summary only after an explicit user click",
        "Pattern work must keep Pattern A/B/C as independent editable event data",
        "Pattern Compare work must derive event, track, and arrangement-use summaries from local Pattern A/B/C and arrangement state",
        "Cue must switch only selected-pattern preview state without autoplay or undo history",
        "Use must route selected-block pattern changes through existing undoable arrangement updates",
        "Copy and clear tools must operate on the selected pattern slot",
        "Pattern preview playback should loop the selected pattern",
        "arrangement playback and WAV export should follow arrangement pattern assignments",
        "Pattern variation work must be deterministic",
        "operate only on the selected Pattern A/B/C slot through undoable project history",
        "keep generated drums, bass, melody, chords, velocities, timings, repeats, and probabilities manually editable",
        "Pattern Fill work must be deterministic",
        "keep Drum Fill/808 Pickup/Melody Turn/Clear Tail results manually editable",
        "Melody Motif Pad work must derive Synth melody notes from the current key after an explicit click",
        "Delivery Target work must store the selected fixed or custom target in local project state",
        "bounded default custom target",
        "keep target selection and custom target editing separate from target alignment",
        "Session Brief work must store bounded artist, vibe, reference, and notes text in local project state",
        "Beat Readiness work must derive checks from editable Pattern A/B/C, arrangement, and deterministic export analysis data",
        "remain read-only, avoid mutating project state or generating musical events",
        "Beat Map work must derive workflow stages, song/pattern metrics, Session Brief status, export state, stem state, and action suggestions only from local project state, selected Delivery Target",
        "Next Move work must derive deterministic recommendations from local project, Beat Readiness, and export analysis state",
        "Next Move Pattern Chain work must recommend Pattern Chain only from local readiness state",
        "keep Full Beat available as an explicit alternative when arrangement structure is weak",
        "run only after explicit user button clicks",
        "route mutating actions through undoable project update paths",
        "Selected note edit tool work must keep 808 and Synth note move, transpose, octave, and duplicate actions scoped to the selected Pattern A/B/C slot",
        "preserve length/glide/velocity/chance fields",
        "avoid overlapping duplicate notes at the same step and pitch",
        "Arrangement editor work must let users change a block's section",
        "bar length, and energy",
        "Arrangement track mute work must migrate older arrangement blocks to no muted tracks",
        "keep mutes scoped to the selected block without mutating Pattern A/B/C events",
        "apply the same mute decisions to realtime arrangement playback, full-mix WAV export, and stem export",
        "Arrangement structure work must preserve at least one block",
        "Arrangement split work must split only the selected arrangement block",
        "preserve total arrangement bars",
        "Arrangement merge work must merge only the selected block with the next block",
        "keep the selected block's section",
        "Arrangement template work must replace only arrangement blocks",
        "align the selected pattern with the first template block",
        "make WAV/stem export follow the applied template length",
        "Pattern Chain work must replace only arrangement blocks with deterministic Pattern A/B/C sequences",
        "Pattern Chain step editor work must cycle only arrangement block Pattern A/B/C assignments through existing undoable project update paths",
        "keep each block's section, bars, energy, muted tracks, and Pattern A/B/C musical event data intact",
        "Pattern Chain expand work must transform only arrangement blocks into a longer deterministic song-form outline",
        "make realtime playback plus WAV/stem/MIDI export follow the chain",
        "Arrangement length work must keep per-block bar counts bounded",
        "migrate older project files without bar counts to one bar per block",
        "make export meter, full-mix WAV export, and stem export follow total arrangement bars",
        "Arrangement playback work must map realtime playback through arrangement blocks",
        "preserving a selected-pattern preview mode",
        "accurate transport status",
        "Transport Loop work must keep Song, selected Block, and Pattern loop scope as explicit local playback state",
        "use selected-block start bar and bar length only for realtime audition",
        "avoid writing loop scope into saved project data",
        "keep WAV/stem/MIDI export plus Handoff Sheet semantics tied to the full arrangement rather than the audition loop",
        "Arrangement energy work must keep Energy as deterministic arrangement-block playback/render interpretation",
        "apply the same gain rule to realtime arrangement playback, WAV export, and stem export",
        "preserve selected-pattern preview at neutral energy",
        "Arrangement Move work must transform only the selected arrangement block's existing energy and mutedTracks state through undoable project history",
        "keep Drop/Build/Hook Lift/Reset deterministic and editable afterward",
        "Arrangement Focus work must derive selected-block summaries from local arrangement and Pattern A/B/C event state",
        "offer only explicit user-clicked Focus presets",
        "update only the selected block's section, Pattern assignment, bar length, energy, and mutedTracks through undoable arrangement paths",
        "Live playback edit work must read current project state while scheduling future steps",
        "already-triggered audio is not rewritten",
        "Undo/redo work must record bounded local project-edit history",
        "keep keyboard shortcuts out of focused inputs",
        "Desktop shortcut work must keep playback, Pattern A/B/C selection, save/open, undo/redo, and selected event deletion scoped to the app window",
        "Keyboard Capture work must route desktop key presses into scale-locked 808 or Synth notes",
        "must route destructive deletion through normal undoable project history",
        "Quick Actions work must remain local and explicit",
        "must keep project/open/save/export actions user-triggered",
        "Volume, pan, mute, solo, master output gain, and preset ceiling controls",
        "Channel EQ work must keep low-cut/air controls in mixer state",
        "Channel dynamics work must keep Drive/Glue controls in mixer state",
        "FX send work must keep Space/send controls in mixer state",
        "simplified compression honestly",
        "full-mix WAV export, and stem export",
        "sample import, chopping, sampler tracks, or audio warping",
        "Concept correction work must make the all-genre beat-production mini DAW framing explicit",
        "sample import, chopping, pitch/stretch, one-shot mapping, and sampler workflows are optional later paths",
        "First-run UX, default navigation, and roadmap work must lead with direct beat composition",
        "Sample browsing, chopping, sampler setup, audio clips, and audio warping must stay opt-in optional-sampling paths",
        "core clips are pattern, MIDI, or automation containers",
    ],
    "docs/architecture/product-architecture.md": [
        "The architecture follows a direct-composition pipeline first",
        "Optional sampling attaches after this pipeline as an additional sound source or instrument layer",
        "Pattern/Event Clips",
        "SessionBrief",
        "bounded local artist, vibe, reference, and notes text for project intent and handoff context",
        "not an imported audio asset",
        "Sampling architecture should attach to the beat workstation",
        "The core architecture should remain valid with no audio-file entities at all.",
        "Key and scale changes are composition edits over musical event data.",
        "sample browsing, chopping, sampler mapping, and audio warping belong behind explicit optional-sampling entry points",
        "Roadmap and architecture plans should treat `audio` and `sampler` as extension track types until the direct beat workstation is already useful.",
        "Extension track types for optional sampling, later:",
    ],
    "harness/scripts/run_qa.py": [
        '".worktree/"',
    ],
    "docs/references/official-sources.md": [
        "W3C Web Audio API",
        "Electron Docs",
        "Vite Guide",
        "ITU-R BS.1770",
        "Source Gaps",
    ],
    "package.json": [
        "\"desktop\"",
        "\"typecheck\"",
        "\"build\"",
    ],
    "electron/main.ts": [
        "nodeIntegration: false",
        "contextIsolation: true",
        "sandbox: true",
        "grooveforge:save-project",
        "grooveforge:open-project",
    ],
    "electron/preload.ts": [
        "saveProject",
        "openProject",
    ],
    "src/ui/App.tsx": [
        "Guided",
        "Studio",
        "exportMidi",
        "exportWav",
        "exportStems",
        "analyzeExport",
        "ExportMeter",
        "export-meter-status",
        "export-peak-db",
        "export-rms-db",
        "export-headroom-db",
        "export-limiter-percent",
        "master-ceiling",
        "startRealtimePlayback",
        "getProject: () => projectRef.current",
        "metronome-toggle",
        "toggleMetronome",
        "PlaybackMode",
        "TransportLoopScope",
        "transportLoopScope",
        "transportLoopMode",
        "transportLoopBars",
        "transportLoopStartBar",
        "transportLoopReadout",
        "selectTransportLoopScope",
        "transportLoopLabel",
        "transportLoopStatus",
        "arrangementStartBar",
        "playbackMode",
        "playback-mode-arrangement",
        "transport-loop-block",
        "playback-mode-pattern",
        "transportPrimary",
        "transportSecondary",
        "currentPatternStep",
        "createStylePatternSet",
        "styleSoundPreset",
        "StyleInspector",
        "style-inspector",
        "style-select",
        "style-quick-picks",
        "style-quick-${profile.id}",
        "onSelectStyle(profile.id)",
        "aria-pressed={selected}",
        "createStyleInspectorSummary",
        "styleDensityLabel",
        "bassStyleRoleLabel",
        "melodyStyleRoleLabel",
        "Applied ${nextStyle.name} groove",
        "BeatBlueprintId",
        "BeatBlueprints",
        "applyBeatBlueprint",
        "applySelectedBeatBlueprint",
        "beatBlueprints",
        "beat-blueprints",
        "beat-blueprint-current",
        "beat-blueprint-${blueprint.id}",
        "retargetProjectKey",
        "applyProjectKey",
        "Retargeted project to ${key}",
        "DrumStepInspector",
        "drum-probability",
        "drum-probability-input",
        "drum-chance-badge-${lane}-${step}",
        "updateSelectedDrumProbability",
        "chance / ${timingLabel",
        "selectedDrumStep",
        "updateSelectedDrumVelocity",
        "updateSelectedHatRepeat",
        "drum-velocity",
        "drum-velocity-input",
        "drum-timing-early",
        "drum-timing-on",
        "drum-timing-late",
        "drum-timing-input",
        "updateSelectedDrumTiming",
        "applySelectedDrumGroove",
        "groove-preset-${preset}",
        "timingLabel",
        "timingBadge",
        "hat-repeat-${repeat}",
        "undoStack",
        "redoStack",
        "undoProject",
        "redoProject",
        "ProjectSnapshot",
        "ProjectSnapshots",
        "saveCurrentSnapshot",
        "restoreSavedSnapshot",
        "deleteSavedSnapshot",
        "commitSnapshotName",
        "snapshotNameDrafts",
        "snapshot-name-${snapshot.id}",
        "handleDesktopShortcut",
        "deleteSelectedEvent",
        "deleteSelectedNote",
        "clearSelectedDrumStep",
        "wantsSave",
        "wantsOpen",
        "event.code === \"Space\"",
        "patternShortcut",
        "undo-button",
        "redo-button",
        "isEditableShortcutTarget",
        "historyLimit",
        "NoteEditor",
        "MelodyMotifId",
        "MelodyMotifOption",
        "melodyMotifDefinitions",
        "melodyMotifOptions",
        "MelodyMotifPads",
        "createMelodyMotifOptions",
        "createMelodyMotifNotes",
        "applyMelodyMotif",
        "melody-motif-${motif.id}",
        "melody-motif-pads",
        "KeyboardCapturePanel",
        "keyboardCaptureKeys",
        "keyboardCaptureEnabled",
        "keyboardCaptureTarget",
        "captureKeyboardNote",
        "isKeyboardCaptureKey",
        "nextKeyboardCaptureStep",
        "addKeyboardCaptureNote",
        "keyboard-capture-toggle",
        "keyboard-capture-target-bass",
        "keyboard-capture-target-melody",
        "keyboard-capture-key-${item.key}",
        "toggleBassNote",
        "toggleMelodyNote",
        "selectedSameNote",
        "NoteInspector",
        "note-probability",
        "note-probability-input",
        "note-chance-badge-${track}-${step}-${pitch}",
        "updateSelectedNoteProbability",
        "moveSelectedNoteStep",
        "moveSelectedNotePitch",
        "moveSelectedNoteOctave",
        "moveSelectedNoteTo",
        "duplicateSelectedNote",
        "note-nudge-left",
        "note-nudge-right",
        "note-pitch-down",
        "note-pitch-up",
        "note-octave-down",
        "note-octave-up",
        "note-duplicate",
        "adjacentTrackPitch",
        "octaveShiftPitch",
        "nextEmptyStepForPitch",
        "SoundDesigner",
        "SoundControl",
        "commitPercentInput",
        "skipNextBlurCommit",
        "applySoundPreset",
        "updateSoundDesign",
        "sound-preset-readout",
        "sound-preset-${preset}",
        "sound-${id}-input",
        "bass-drive",
        "sidechain-duck",
        "sound-duck-readout",
        "chord-width",
        "ChordEditor",
        "ChordPadId",
        "ChordPadOption",
        "chordPadDefinitions",
        "chordPadOptions",
        "createChordPadOptions",
        "applyChordPad",
        "chord-pad-${pad.id}",
        "chord-pad-row",
        "chordInversions",
        "chordInversionLabel",
        "ChordProgressionPreset",
        "selectedChordIndex",
        "selectChordEvent",
        "chordProgressionPresetIds",
        "chordProgressionPresetLabel",
        "createChordProgressionPreset",
        "createNextChordEvent",
        "applyChordProgressionPreset",
        "addChordEvent",
        "deleteChordEvent",
        "deleteSelectedChordEvent",
        "updateChordEvent",
        "moveSelectedChordStep",
        "duplicateSelectedChord",
        "moveSelectedChordInversion",
        "chordEventWithUpdate",
        "sameChordEvent",
        "findChordEventIndex",
        "nextEmptyChordStep",
        "chord-preset-${preset}",
        "chord-add",
        "chord-delete",
        "chord-move-left",
        "chord-move-right",
        "chord-duplicate",
        "chord-invert-down",
        "chord-invert-up",
        "chord-step",
        "chord-root",
        "chord-quality",
        "chord-inversion",
        "chord-inversion-badge",
        "chord-length-input",
        "chord-velocity-input",
        "chord-probability-input",
        "chord-chance-badge-${index}",
        "chanceBadgeLabel",
        "compactChanceBadgeLabel",
        "handleSaveProject",
        "handleOpenProject",
        "handleExportMidi",
        "Exported MIDI",
        "handleExportHandoffSheet",
        "createHandoffSheet",
        "handoffSheetFileName",
        "downloadTextFile",
        "Exported ${fileName}",
        "handleExportStems",
        "export-midi",
        "export-handoff-sheet",
        "export-stems",
        "Invalid project file",
        "patternEventCount",
        "BeatReadiness",
        "BeatReadinessCheck",
        "createBeatReadinessChecks",
        "DeliveryTargets",
        "DeliveryTargetId",
        "CustomDeliveryTarget",
        "activeDeliveryTarget",
        "selectDeliveryTarget",
        "alignDeliveryTarget",
        "updateCustomDeliveryTarget",
        "sameCustomDeliveryTarget",
        "boundedCustomDeliveryText",
        "mixPostureOptions",
        "delivery-targets",
        "delivery-target-current",
        "delivery-target-custom",
        "delivery-target-set-${target.id}",
        "delivery-target-align-${target.id}",
        "delivery-target-set-custom",
        "delivery-target-align-custom",
        "custom-target-name",
        "custom-target-focus",
        "custom-target-bars",
        "custom-target-stems",
        "custom-target-template",
        "custom-target-master",
        "custom-target-posture",
        "deliveryTargetNextMoveAction",
        '"deliveryTarget"',
        "SessionBrief",
        "SessionBriefPanel",
        "updateSessionBrief",
        "clearSessionBrief",
        "sessionBriefStatus",
        "sessionBriefFilledFields",
        "boundedSessionBriefText",
        "session-brief",
        "session-brief-artist",
        "session-brief-vibe",
        "session-brief-reference",
        "session-brief-notes",
        "session-brief-clear",
        "BeatMap",
        "BeatMapSummary",
        "BeatMapStage",
        "BeatMapMetric",
        "createBeatMapSummary",
        "createBeatMapStages",
        "createBeatMapMetrics",
        "createBeatMapActions",
        "chainExpandNextMoveAction",
        "usedPatternSlots",
        "audibleStemTracks",
        "weakestTone",
        "NextMove",
        "NextMoveAction",
        "NextMoveCommand",
        "createNextMoveActions",
        "primaryNextMoveAction",
        "patternChainNextMoveAction",
        "fullArrangementNextMoveAction",
        "runNextMove",
        '"patternChain"',
        '"chainExpand"',
        "Sketch an 8-bar Pattern Chain",
        "Beat Map",
        "beat-map",
        "beat-map-headline",
        "beat-map-stages",
        "beat-map-metrics",
        "beat-map-action-${action.id}",
        "next-move",
        "next-move-title",
        "next-move-action-${primaryAction.id}",
        "Review Mix Coach",
        "QuickAction",
        "QuickActions",
        "quickActionsOpen",
        "quickActionQuery",
        "wantsQuickActions",
        "openQuickActions",
        "closeQuickActions",
        "runQuickAction",
        "createQuickActions",
        "filterQuickActions",
        "quickActionSearchTokens",
        "quick-actions-open",
        "quick-actions",
        "quick-actions-search",
        "quick-action-${action.id}",
        "arrangedPatternData",
        "drumHitCount",
        "drumReadinessCheck",
        "bassReadinessCheck",
        "harmonyReadinessCheck",
        "arrangementReadinessCheck",
        "exportReadinessCheck",
        "beatReadinessChecks",
        "project-snapshots",
        "snapshot-count",
        "snapshot-save",
        "snapshot-empty",
        "snapshot-item-${snapshot.id}",
        "snapshot-restore-${snapshot.id}",
        "snapshot-delete-${snapshot.id}",
        "beat-readiness",
        "beat-readiness-summary",
        "beat-readiness-check-${check.id}",
        "PatternCompareSummary",
        "PatternCompareStrip",
        "patternCompareSummaries",
        "createPatternCompareSummaries",
        "cuePattern",
        "usePatternInSelectedBlock",
        "selectPattern",
        "copySelectedPattern",
        "clearSelectedPattern",
        "applyPatternVariation",
        "applyPatternFill",
        "patternVariationPresetIds",
        "patternVariationPresetLabel",
        "patternFillPresetIds",
        "patternFillPresetLabel",
        "applyPatternFillPreset",
        "pattern-copy-${pattern}",
        "pattern-compare",
        "pattern-compare-${summary.slot}",
        "pattern-cue-${summary.slot}",
        "pattern-use-${summary.slot}",
        "pattern-variation-${preset}",
        "pattern-fill-${preset}",
        "pattern-clear",
        "selectedArrangementIndex",
        "ArrangementTemplateId",
        "arrangementTemplateIds",
        "arrangementTemplateLabel",
        "PatternChainId",
        "patternChainIds",
        "patternChainLabel",
        "createPatternChain",
        "expandPatternChainArrangement",
        "applyPatternChain",
        "expandPatternChain",
        "cyclePatternChainStep",
        "patternChainReadout",
        "nextPatternSlot",
        "pattern-chain-current",
        "pattern-chain-${chain}",
        "pattern-chain-expand",
        "pattern-chain-step-editor",
        "pattern-chain-step-${index}",
        "pattern-chain-step-pattern-${index}",
        "ArrangementMovePreset",
        "ArrangementFocusPresetId",
        "ArrangementFocusPanel",
        "ArrangementFocusSummary",
        "arrangementFocusPresets",
        "selectedArrangementFocus",
        "createArrangementFocusSummary",
        "suggestedArrangementFocusPreset",
        "applyArrangementFocusPreset",
        "arrangementMovePresetIds",
        "arrangementMovePresetLabel",
        "applyArrangementMovePreset",
        "applyArrangementMoveToSelected",
        "arrangementMuteTrackIds",
        "arrangementMuteTrackLabel",
        "arrangementTotalBars",
        "createArrangementTemplate",
        "minArrangementBars",
        "maxArrangementBars",
        "arrangementEnergyGain",
        "normalizeArrangementEnergy",
        "normalizeArrangementMutedTracks",
        "normalizeArrangementBars",
        "applyArrangementTemplate",
        "updateArrangementBlock",
        "toggleArrangementTrackMute",
        "duplicateArrangementBlock",
        "splitArrangementBlock",
        "mergeArrangementBlock",
        "canMergeArrangementBlock",
        "selectedArrangementNextBlock",
        "splitAfterBars",
        "clampSplitAfterBars",
        "moveArrangementBlock",
        "deleteArrangementBlock",
        "Merged arrangement blocks",
        "Selected arrangement block editor",
        "arrangement-template-${template}",
        "arrangement-section-select",
        "arrangement-bars-input",
        "arrangement-split-after",
        "arrangement-split",
        "arrangement-merge",
        "arrangement-energy-input",
        "arrangement-move-${preset}",
        "arrangement-focus",
        "arrangement-focus-summary",
        "arrangement-focus-${preset.id}",
        "hook-peak-focus",
        "arrangement-track-mute-${track}",
        "arrangement-duplicate",
        "arrangement-delete",
        "barCountLabel",
        "updateMixerChannel",
        "normalizeMixerEq",
        "mixer-low-cut",
        "mixer-low-cut-input",
        "mixer-air",
        "mixer-air-input",
        "mixer-drive",
        "mixer-drive-input",
        "mixer-glue",
        "mixer-glue-input",
        "mixer-send",
        "mixer-send-input",
        "Cut {percentLabel(channel.lowCut)}",
        "Air {percentLabel(channel.air)}",
        "Drive {percentLabel(channel.drive)}",
        "Glue {percentLabel(channel.glue)}",
        "Space {percentLabel(channel.send)}",
        "StemLevelMeter",
        "analyzeStemExports",
        "stemAnalyses",
        "isStemTrackId",
        "stem-level-meter-${trackId}",
        "stem-peak-db-${trackId}",
        "stem-rms-db-${trackId}",
        "stem-headroom-db-${trackId}",
        "MixCoach",
        "MixCoachCheck",
        "MixFixPreset",
        "MixFixAction",
        "applyMixFixPreset",
        "createMixFixActions",
        "applyMixFixToProject",
        "mixFixPresetLabel",
        "mix-fix-${fix.preset}",
        '"headroom"',
        '"stem_balance"',
        '"low_end"',
        "createMixCoachChecks",
        "masterHeadroomCheck",
        "limiterCheck",
        "stemBalanceCheck",
        "lowEndBlendCheck",
        "mixCoachSummary",
        "mix-coach",
        "mix-coach-summary",
        "mix-coach-check-${check.id}",
        "applyMasterPreset",
        "mixer-pan",
        "mixer-pan-input",
        "mixer-solo",
    ],
    "src/audio/scheduler.ts": [
        "scheduleAheadSeconds",
        "startRealtimePlayback",
        "getProject",
        "currentProject",
        "masterGain.gain.setTargetAtTime",
        "scheduleMetronomeClick",
        "metronomeEnabled",
        "PlaybackMode",
        "playbackContextForStep",
        "startBar",
        "options.startBar",
        "arrangementContextForBar",
        "arrangementEnergyGain",
        "energyGain",
        "mutedTracks",
        "arrangementTrackMix",
        "onStep",
        "activePattern",
        "chordPitches",
        "SoundDesign",
        "drumStepTimingMs",
        "drumStepVelocity",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "hatRepeatCount",
        "sidechainGainForStep",
        "lowCut",
        "air",
        "drive",
        "glue",
        "channelHighpassHz",
        "channelAirFilterHz",
        "connectChannelGlue",
        "driveCurve",
        "channelMix",
        "createSpaceBus",
        "connectScheduledOutput",
        "createStereoPanner",
    ],
    "src/audio/render.ts": [
        "patternForSlot",
        "arrangementBlock",
        "arrangementBarCount",
        "arrangementBlockForBar",
        "arrangementTotalBars",
        "arrangementEnergyGain",
        "energyGain",
        "arrangementBlockMutesTrack",
        "mutedChannelMix",
        "arrangementChannelMix",
        "createRenderNoiseSeed",
        "seededNoiseSample",
        "hashString",
        "hashNumbers",
        "normalizeArrangementBars",
        "chordPitches",
        "SoundDesign",
        "drumStepTimingMs",
        "drumStepVelocity",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "hatRepeatCount",
        "sidechainGainForStep",
        "lowCut",
        "air",
        "drive",
        "glue",
        "send",
        "spaceSendMix",
        "addToneWithSend",
        "addNoiseWithSend",
        "applySpaceReturn",
        "channelHighpassHz",
        "channelDriveSample",
        "channelGlueSample",
        "toneEqFactor",
        "addTone",
        "channelMix",
        "masterOutputGain",
        "stemTrackIds",
        "StemTrackId",
        "StemExportAnalyses",
        "ExportAnalysis",
        "analyzeExport",
        "analyzeStemExports",
        "exportStems",
        "stemTrackLabel",
    ],
    "src/audio/midi.ts": [
        "createMidiFile",
        "exportMidi",
        "midiFileName",
        "MThd",
        "MTrk",
        "ticksPerQuarter",
        "ticksPerStep",
        "arrangementBlockForBar",
        "arrangementBlockMutesTrack",
        "arrangementEnergyGain",
        "drumStepShouldPlay",
        "hatRepeatCount",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "chordPitches",
        "GrooveForge Drums",
        "GrooveForge 808",
        "GrooveForge Synth",
        "GrooveForge Chords",
        "audio/midi",
    ],
    "src/domain/workstation.ts": [
        "styleProfiles",
        '"jersey"',
        '"phonk"',
        "Jersey Club",
        "Phonk",
        "starterProject",
        "StyleProfile",
        "DeliveryTarget",
        "DeliveryTargetId",
        "FixedDeliveryTargetId",
        "CustomDeliveryTarget",
        "MixPosture",
        "SessionBrief",
        "sessionBrief",
        "defaultSessionBrief",
        "maxSessionBriefFieldLength",
        "maxSessionBriefNotesLength",
        "maxCustomDeliveryTargetNameLength",
        "maxCustomDeliveryTargetFocusLength",
        "minDeliveryTargetBars",
        "maxDeliveryTargetBars",
        "minDeliveryTargetStemGoal",
        "maxDeliveryTargetStemGoal",
        "normalizeSessionBrief",
        "normalizeBriefText",
        "isSessionBriefInput",
        "customDeliveryTarget",
        "fixedDeliveryTargetIds",
        "deliveryTargetIds",
        "deliveryTargets",
        "deliveryTargetLabels",
        "defaultDeliveryTarget",
        "defaultCustomDeliveryTarget",
        "deliveryTargetLabel",
        "deliveryTargetFocus",
        "deliveryTargetForId",
        "activeDeliveryTarget",
        "applyDeliveryTarget",
        "applyDeliveryTargetMixer",
        "normalizeDeliveryTargetId",
        "normalizeCustomDeliveryTarget",
        "normalizeDeliveryTargetBars",
        "normalizeDeliveryTargetStemGoal",
        "CustomDeliveryTargetInput",
        "isCustomDeliveryTargetInput",
        "isMixPosture",
        "metronomeEnabled",
        "bassPitchLanes",
        "melodyPitchLanes",
        "scalePitches",
        "retargetPitchNameToKey",
        "retargetPitchToKey",
        "retargetPatternKey",
        "retargetProjectKey",
        "serializeProjectFile",
        "parseProjectFile",
        "PatternData",
        "ProjectCoreState",
        "ProjectSnapshot",
        "maxProjectSnapshots",
        "maxProjectSnapshotNameLength",
        "nextProjectSnapshotName",
        "normalizeProjectSnapshotName",
        "createProjectSnapshot",
        "saveProjectSnapshot",
        "restoreProjectSnapshot",
        "deleteProjectSnapshot",
        "renameProjectSnapshot",
        "projectSnapshotSummary",
        "normalizeProjectSnapshots",
        "cloneProjectCore",
        "DrumVelocities",
        "DrumTimings",
        "DrumProbabilities",
        "probability: number",
        "DrumGroovePreset",
        "drumGroovePresetIds",
        "drumGroovePresetLabel",
        "applyDrumGroovePreset",
        "PatternVariationPreset",
        "patternVariationPresetIds",
        "patternVariationPresetLabel",
        "createPatternVariation",
        "PatternFillPreset",
        "patternFillPresetIds",
        "patternFillPresetLabel",
        "applyPatternFillPreset",
        "clearPatternTail",
        "drumStepTimingMs",
        "drumStepVelocity",
        "normalizeDrumTimingMs",
        "grooveVelocity",
        "grooveTimingMs",
        "hatRepeatCount",
        "drumStepProbability",
        "drumStepShouldPlay",
        "noteEventShouldPlay",
        "chordEventShouldPlay",
        "normalizeDrumProbability",
        "normalizeEventProbability",
        "normalizeDrumVelocity",
        "normalizeHatRepeat",
        "sidechainGainForStep",
        "ChordEvent",
        "chordQualities",
        "ChordInversion",
        "chordInversions",
        "chordInversionLabel",
        "normalizeChordInversion",
        "chordPitches",
        "SoundDesign",
        "soundPresetIds",
        "soundPresetDesign",
        "soundPresetLabel",
        "patternSlots",
        "createStylePatternSet",
        "styleSoundPreset",
        "stylePatternBlueprints",
        "BeatBlueprint",
        "BeatBlueprintId",
        "beatBlueprintIds",
        "beatBlueprints",
        "applyBeatBlueprint",
        "applyBeatBlueprintMixer",
        "createEmptyPatternData",
        "ArrangementSection",
        "ArrangementMuteTrack",
        "ArrangementMovePreset",
        "arrangementMovePresetIds",
        "arrangementMovePresetLabel",
        "arrangementMovePresetLabels",
        "applyArrangementMovePreset",
        "arrangementMuteTrackIds",
        "arrangementMuteTrackLabel",
        "arrangementBlockMutesTrack",
        "normalizeArrangementMutedTracks",
        "arrangementSections",
        "minArrangementBars",
        "maxArrangementBars",
        "normalizeArrangementEnergy",
        "arrangementEnergyGain",
        "normalizeArrangementBars",
        "arrangementTotalBars",
        "masterPresets",
        "masterPresetCeilingDb",
        "normalizeProjectState",
        "MixerChannelInput",
        "normalizeMixerEq",
        "normalizeMixerChannels",
        "lowCut",
        "air",
        "drive",
        "glue",
        "send",
    ],
}


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def check_required_paths(errors: list[str]) -> None:
    for path in REQUIRED_PATHS:
        if not (ROOT / path).exists():
            errors.append(f"missing required path: {path}")


def check_root_markdown(errors: list[str]) -> None:
    allowed = {"README.md", "AGENTS.md"}
    found = {path.name for path in ROOT.glob("*.md")}
    extra = sorted(found - allowed)
    if extra:
        errors.append(f"unexpected root markdown files: {', '.join(extra)}")


def check_forbidden_paths(errors: list[str]) -> None:
    if (ROOT / "docs/plan").exists():
        errors.append("forbidden path exists: docs/plan")


def check_plan_names(errors: list[str]) -> None:
    for directory in [
        ROOT / "docs/exec_plans/active",
        ROOT / "docs/exec_plans/completed",
    ]:
        if not directory.exists():
            continue
        for path in directory.glob("*.md"):
            if not PLAN_RE.fullmatch(path.name):
                errors.append(f"invalid plan filename: {rel(path)}")


def check_text_expectations(errors: list[str]) -> None:
    for file_path, needles in TEXT_EXPECTATIONS.items():
        text = (ROOT / file_path).read_text(encoding="utf-8")
        for needle in needles:
            if needle not in text:
                errors.append(f"{file_path} missing text: {needle}")


def check_official_sources(errors: list[str]) -> None:
    text = (ROOT / "docs/references/official-sources.md").read_text(encoding="utf-8")
    if "| TODO |" in text:
        errors.append("official sources still contain placeholder table rows")


def check_strict_todos(errors: list[str]) -> None:
    ignored_prefixes = {
        ".worktree/",
        "dist/",
        "dist-electron/",
        "harness/templates/",
        "node_modules/",
    }
    for path in ROOT.rglob("*.md"):
        relative = rel(path)
        if any(relative.startswith(prefix) for prefix in ignored_prefixes):
            continue
        text = path.read_text(encoding="utf-8")
        if "TODO" in text:
            errors.append(f"strict mode found TODO in {relative}")


def check_offline_render_determinism(errors: list[str]) -> None:
    render_text = (ROOT / "src/audio/render.ts").read_text(encoding="utf-8")
    if "Math.random" in render_text:
        errors.append("src/audio/render.ts must not use Math.random in the offline render path")


def run_checks(strict: bool = False) -> list[str]:
    errors: list[str] = []
    check_required_paths(errors)
    check_root_markdown(errors)
    check_forbidden_paths(errors)
    check_plan_names(errors)
    check_text_expectations(errors)
    check_official_sources(errors)
    check_offline_render_determinism(errors)
    if strict:
        check_strict_todos(errors)
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate the GrooveForge project base.")
    parser.add_argument("--strict", action="store_true", help="Fail on TODO markers outside templates.")
    args = parser.parse_args(argv)

    errors = run_checks(strict=args.strict)
    if errors:
        print("QA failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    mode = "strict " if args.strict else ""
    print(f"GrooveForge {mode}QA passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
